{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_debug",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_debug-30.0.aar",
          "url": "beacon_debug-30.0.aar",
          "size": 48385,
          "sha512": "3c0ce33c70d1efb14c21201aaae2095eeb82625a27d7b5291ee1b3d0b4a8f666c87533375e706dd98599238a98e9c0367d0d70f79c62e6fbb0a261b51ddae3fe",
          "sha256": "86e4b33b03aa47f16bf5d3a904c8bc9c647650c3334a6441cdc0c26f8d881be9",
          "sha1": "2a7d6fb31bd9d41f0c4f78dffbb4458d108450ad",
          "md5": "064ce4c98d298c40cf5f4860084e7b5e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_debug-30.0.aar",
          "url": "beacon_debug-30.0.aar",
          "size": 48385,
          "sha512": "3c0ce33c70d1efb14c21201aaae2095eeb82625a27d7b5291ee1b3d0b4a8f666c87533375e706dd98599238a98e9c0367d0d70f79c62e6fbb0a261b51ddae3fe",
          "sha256": "86e4b33b03aa47f16bf5d3a904c8bc9c647650c3334a6441cdc0c26f8d881be9",
          "sha1": "2a7d6fb31bd9d41f0c4f78dffbb4458d108450ad",
          "md5": "064ce4c98d298c40cf5f4860084e7b5e"
        }
      ]
    }
  ]
}
