{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_debug",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-30.0.aar",
          "url": "core_debug-30.0.aar",
          "size": 37234,
          "sha512": "c57c40037af4b7ab391c0642ef822ea3c69cdcd785f7a3aa03ef308b78d3d2ba5a00513135d394f3c4064ea6b81b99821ef71c914e4a9f5d8b07bb4db489767c",
          "sha256": "a367217426dab1ed01764c16849211b7bd883dde5e94ed0c2b51dba3cd069954",
          "sha1": "6ef323dbf59d7de48823c1970b0aecc1fcfa0e26",
          "md5": "b9f48c78f865896f0bbd7ecdb8d494be"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber_debug",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "30.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-30.0.aar",
          "url": "core_debug-30.0.aar",
          "size": 37234,
          "sha512": "c57c40037af4b7ab391c0642ef822ea3c69cdcd785f7a3aa03ef308b78d3d2ba5a00513135d394f3c4064ea6b81b99821ef71c914e4a9f5d8b07bb4db489767c",
          "sha256": "a367217426dab1ed01764c16849211b7bd883dde5e94ed0c2b51dba3cd069954",
          "sha1": "6ef323dbf59d7de48823c1970b0aecc1fcfa0e26",
          "md5": "b9f48c78f865896f0bbd7ecdb8d494be"
        }
      ]
    }
  ]
}
