{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-30.0.aar",
          "url": "system_uptime_release-30.0.aar",
          "size": 5438,
          "sha512": "b731d411cf92a7add1cc0d60e498801362a68ca8ff1af9b3e36273152b0e04df22dcb525e78d1081f2791666e8347722f404ef5c157047809f047a0ac2f7d6fc",
          "sha256": "be3b19b8b78271a191d7c33df90cdc31182aeb74c27c3246b27a519f0d476982",
          "sha1": "2ff7f18749224420f325c4559a27278408a738bc",
          "md5": "2eca5c9529efba0b22362795c87b8017"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-30.0.aar",
          "url": "system_uptime_release-30.0.aar",
          "size": 5438,
          "sha512": "b731d411cf92a7add1cc0d60e498801362a68ca8ff1af9b3e36273152b0e04df22dcb525e78d1081f2791666e8347722f404ef5c157047809f047a0ac2f7d6fc",
          "sha256": "be3b19b8b78271a191d7c33df90cdc31182aeb74c27c3246b27a519f0d476982",
          "sha1": "2ff7f18749224420f325c4559a27278408a738bc",
          "md5": "2eca5c9529efba0b22362795c87b8017"
        }
      ]
    }
  ]
}
