{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xuning.native_font",
    "module": "native_font_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_profile-26.0.aar",
          "url": "native_font_profile-26.0.aar",
          "size": 5926,
          "sha512": "9f93cda16eeb556de368fbe7d4cce62aeff31c48d1fb4b2e16f86c15a89b9bdbb9d28a2c9831383aca90618d014984e8f1808c41a3dbf0a354f5f64bd7869aa5",
          "sha256": "3bb718bbb6da64f422a9cb60a52d2f8d52551fad03c88816c95d11fb867cc5fd",
          "sha1": "8c32a51b3407e9abaf7b473b2283b3d7e77d3216",
          "md5": "1fb5d9a792ed384f8f4c96bd5eb088d5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_profile-26.0.aar",
          "url": "native_font_profile-26.0.aar",
          "size": 5926,
          "sha512": "9f93cda16eeb556de368fbe7d4cce62aeff31c48d1fb4b2e16f86c15a89b9bdbb9d28a2c9831383aca90618d014984e8f1808c41a3dbf0a354f5f64bd7869aa5",
          "sha256": "3bb718bbb6da64f422a9cb60a52d2f8d52551fad03c88816c95d11fb867cc5fd",
          "sha1": "8c32a51b3407e9abaf7b473b2283b3d7e77d3216",
          "md5": "1fb5d9a792ed384f8f4c96bd5eb088d5"
        }
      ]
    }
  ]
}
