{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_release-v1.0.0.aar",
          "url": "screenshot_prevention_release-v1.0.0.aar",
          "size": 31365,
          "sha512": "130a21ca89d8276db851aa3293b75cf901dce4fcbd62ec159fbdb96819684ed88116d6e0491a388c8fa0c2f9e4248d2f41252c8f01bfc1639f32775922560d70",
          "sha256": "c832af5dbd289d53cfed73d6eaedbd7e9d0bbbf8c82670270adae2aa5b145474",
          "sha1": "6e7a489fed7881e07a338595906940443810bb3a",
          "md5": "4fcf4359330126392cda88d4bd72319a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "v1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_release-v1.0.0.aar",
          "url": "screenshot_prevention_release-v1.0.0.aar",
          "size": 31365,
          "sha512": "130a21ca89d8276db851aa3293b75cf901dce4fcbd62ec159fbdb96819684ed88116d6e0491a388c8fa0c2f9e4248d2f41252c8f01bfc1639f32775922560d70",
          "sha256": "c832af5dbd289d53cfed73d6eaedbd7e9d0bbbf8c82670270adae2aa5b145474",
          "sha1": "6e7a489fed7881e07a338595906940443810bb3a",
          "md5": "4fcf4359330126392cda88d4bd72319a"
        }
      ]
    }
  ]
}
