{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-26.0.aar",
          "url": "sqflite_debug-26.0.aar",
          "size": 44249,
          "sha512": "5781e397f82f88b2bdc403b5f689a2f35458e6bbcda3648600c7da21d7a9b41bcb816662f9a531745085eb6d71a535f725369e95ee3462281425306c9252f417",
          "sha256": "22ce713c18b52ea74166a0f0f1d0fc7b1f964f373700b1e7087e95093e0d1722",
          "sha1": "8b9918e782fddbc3c13cd0a0fc0733db5506ce8f",
          "md5": "48eadbf1beb4f628fd7f26e381c5b9fb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-26.0.aar",
          "url": "sqflite_debug-26.0.aar",
          "size": 44249,
          "sha512": "5781e397f82f88b2bdc403b5f689a2f35458e6bbcda3648600c7da21d7a9b41bcb816662f9a531745085eb6d71a535f725369e95ee3462281425306c9252f417",
          "sha256": "22ce713c18b52ea74166a0f0f1d0fc7b1f964f373700b1e7087e95093e0d1722",
          "sha1": "8b9918e782fddbc3c13cd0a0fc0733db5506ce8f",
          "md5": "48eadbf1beb4f628fd7f26e381c5b9fb"
        }
      ]
    }
  ]
}
