{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wongpiwat.trust_location",
    "module": "trust_location_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_debug-26.0.aar",
          "url": "trust_location_debug-26.0.aar",
          "size": 35833,
          "sha512": "f5b130a363a343c530423452591882a465fd2378e3098c74598c5dc408e549fa8350efc9b5f5fc5046bf3c3baa852112685ed1f36ddb1eb19b1baf586ca4bfed",
          "sha256": "daf77f37940803dae97dfe5ef1709791df517890bc35fd231ca22e8831ea942e",
          "sha1": "cf6820a8a7495fb0555386c55bd7188948a69c5c",
          "md5": "dfaff55037c30413c50a4c4608b4899c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_debug-26.0.aar",
          "url": "trust_location_debug-26.0.aar",
          "size": 35833,
          "sha512": "f5b130a363a343c530423452591882a465fd2378e3098c74598c5dc408e549fa8350efc9b5f5fc5046bf3c3baa852112685ed1f36ddb1eb19b1baf586ca4bfed",
          "sha256": "daf77f37940803dae97dfe5ef1709791df517890bc35fd231ca22e8831ea942e",
          "sha1": "cf6820a8a7495fb0555386c55bd7188948a69c5c",
          "md5": "dfaff55037c30413c50a4c4608b4899c"
        }
      ]
    }
  ]
}
