{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-v1.0.0.aar",
          "url": "share_plus_release-v1.0.0.aar",
          "size": 22140,
          "sha512": "465d004aa33925d109976725101d97acc186060b8ffcf1ac0865d5db338b6ba2190867ddb046381295afc01400ce13a4f0604185c295ef3e8c0d87489f922252",
          "sha256": "c50dca6527d0713b82c91b0604297ede8aa234639063e7fd5151d1189027dd97",
          "sha1": "4c84c2c269ab499e81797257130e25918531a279",
          "md5": "1b467701a35884b58a50d4aaebd215b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-v1.0.0.aar",
          "url": "share_plus_release-v1.0.0.aar",
          "size": 22140,
          "sha512": "465d004aa33925d109976725101d97acc186060b8ffcf1ac0865d5db338b6ba2190867ddb046381295afc01400ce13a4f0604185c295ef3e8c0d87489f922252",
          "sha256": "c50dca6527d0713b82c91b0604297ede8aa234639063e7fd5151d1189027dd97",
          "sha1": "4c84c2c269ab499e81797257130e25918531a279",
          "md5": "1b467701a35884b58a50d4aaebd215b9"
        }
      ]
    }
  ]
}
