{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.appsettings",
    "module": "app_settings_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-v1.0.2.aar",
          "url": "app_settings_release-v1.0.2.aar",
          "size": 8061,
          "sha512": "cf75e2a2a502dc6cceefe02d6ffdfd03d2e76cf386f0ac23d3f62785cc5ad762f9eb20e6fa492ed6a599d03874d91a2d1e84a4e0241c88edd75387f5abe426fd",
          "sha256": "5a7c6fcc239b508747be74136f89a85165f909e1aff65b2a90401f39527138c7",
          "sha1": "f0739ee26240a9669803867fb45dc79e63e42751",
          "md5": "01178c332c1ea9d0b903661b29885324"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-v1.0.2.aar",
          "url": "app_settings_release-v1.0.2.aar",
          "size": 8061,
          "sha512": "cf75e2a2a502dc6cceefe02d6ffdfd03d2e76cf386f0ac23d3f62785cc5ad762f9eb20e6fa492ed6a599d03874d91a2d1e84a4e0241c88edd75387f5abe426fd",
          "sha256": "5a7c6fcc239b508747be74136f89a85165f909e1aff65b2a90401f39527138c7",
          "sha1": "f0739ee26240a9669803867fb45dc79e63e42751",
          "md5": "01178c332c1ea9d0b903661b29885324"
        }
      ]
    }
  ]
}
