{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-30.0.aar",
          "url": "beacon_release-30.0.aar",
          "size": 46997,
          "sha512": "2742e99eb288f0a94ce9f11b93a7211db0b930896dedd3b10c03f3ff69f8ea68c0b25564e0aee05958de0665fa1ec064c5b4093fe5c90b297317d38cee0dd3bc",
          "sha256": "b8ebd37035d16dd77cd5ad1c14d2b24cc71c2db3f6eeb1c6cbe0b5f798f5dc1f",
          "sha1": "2a70767358d144b80ef65ae3d72910487c9fd1e9",
          "md5": "cf363a273a2d3690ae482b0ae2d79906"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-30.0.aar",
          "url": "beacon_release-30.0.aar",
          "size": 46997,
          "sha512": "2742e99eb288f0a94ce9f11b93a7211db0b930896dedd3b10c03f3ff69f8ea68c0b25564e0aee05958de0665fa1ec064c5b4093fe5c90b297317d38cee0dd3bc",
          "sha256": "b8ebd37035d16dd77cd5ad1c14d2b24cc71c2db3f6eeb1c6cbe0b5f798f5dc1f",
          "sha1": "2a70767358d144b80ef65ae3d72910487c9fd1e9",
          "md5": "cf363a273a2d3690ae482b0ae2d79906"
        }
      ]
    }
  ]
}
