{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 15721113,
          "sha512": "8704fa60e292ba91f200ce878b0eab19ec35d81f16b2510ff498d0c44e6ef979b1b37d1315d6caba161f254b8ca1269f5556eca632f5ca07262a95799a240f18",
          "sha256": "d2b91b4fab5fdc81a1d1be08601caf6643eb6125c599463bc28c676a4eee61c4",
          "sha1": "0d4dbd93910f35581fd22f573fd67a435b962183",
          "md5": "2fbd6f7653e87e8a03a983c275507bf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 15721113,
          "sha512": "8704fa60e292ba91f200ce878b0eab19ec35d81f16b2510ff498d0c44e6ef979b1b37d1315d6caba161f254b8ca1269f5556eca632f5ca07262a95799a240f18",
          "sha256": "d2b91b4fab5fdc81a1d1be08601caf6643eb6125c599463bc28c676a4eee61c4",
          "sha1": "0d4dbd93910f35581fd22f573fd67a435b962183",
          "md5": "2fbd6f7653e87e8a03a983c275507bf7"
        }
      ]
    }
  ]
}
