{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.appsettings",
    "module": "app_settings_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-1.0.aar",
          "url": "app_settings_release-1.0.aar",
          "size": 8172,
          "sha512": "90a149a6f731db87147437f19c558d5bb4f003cd15ca85f76f0ed7d1f518b86dbda898f0fb49e94ac8064447c7ee5df379f8a032ec5d9105ab5855d2e978cdb8",
          "sha256": "d11a0d8cd80fcae8ac13d15b8d02e1e7a4fdd4ff55f4b218fd2a1753c2dfa4cd",
          "sha1": "de82b30feb848a96db80d3fb4f9867958ee98603",
          "md5": "4c2a82bd35b47cb6f35e655c2d722898"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-1.0.aar",
          "url": "app_settings_release-1.0.aar",
          "size": 8172,
          "sha512": "90a149a6f731db87147437f19c558d5bb4f003cd15ca85f76f0ed7d1f518b86dbda898f0fb49e94ac8064447c7ee5df379f8a032ec5d9105ab5855d2e978cdb8",
          "sha256": "d11a0d8cd80fcae8ac13d15b8d02e1e7a4fdd4ff55f4b218fd2a1753c2dfa4cd",
          "sha1": "de82b30feb848a96db80d3fb4f9867958ee98603",
          "md5": "4c2a82bd35b47cb6f35e655c2d722898"
        }
      ]
    }
  ]
}
