{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_debug",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.0.2.aar",
          "url": "flutter_debug-v1.0.2.aar",
          "size": 24170011,
          "sha512": "2f1a669a3aecaf6e02ce7ae7dc64572b12835670eebe7e450e827414ff409536de4afcedcdafabd00c40f17bf4b067ece5ad457ed08d397f890cd646d414f8d2",
          "sha256": "1b78f261f6ade885cbc2984d44620d39f1e475ad91670618364129cd8bfe40bd",
          "sha1": "12298a80d45544d0d44be481689f35fcdebd8f63",
          "md5": "9fdddca61110e38ca7e66aae6cd45126"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_debug",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_debug",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.0.2.aar",
          "url": "flutter_debug-v1.0.2.aar",
          "size": 24170011,
          "sha512": "2f1a669a3aecaf6e02ce7ae7dc64572b12835670eebe7e450e827414ff409536de4afcedcdafabd00c40f17bf4b067ece5ad457ed08d397f890cd646d414f8d2",
          "sha256": "1b78f261f6ade885cbc2984d44620d39f1e475ad91670618364129cd8bfe40bd",
          "sha1": "12298a80d45544d0d44be481689f35fcdebd8f63",
          "md5": "9fdddca61110e38ca7e66aae6cd45126"
        }
      ]
    }
  ]
}
