{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-v1.0.0.aar",
          "url": "beacon_release-v1.0.0.aar",
          "size": 47103,
          "sha512": "ddb73c41e907201dfc1e6857ef9e8b5398d1270c7add75c250806585685eab7449a0a78b69456c90415f404ebc5bec145465a79622022a90610ea465a45f775f",
          "sha256": "2ac8e9e9b2d690cdce81a88ff7b8214275aac4d5165154d5cf327be08f603f87",
          "sha1": "89658e9b75408e42ea299dbbaf87537c880880b6",
          "md5": "a602455200a2ddb98128360e9bf516ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-v1.0.0.aar",
          "url": "beacon_release-v1.0.0.aar",
          "size": 47103,
          "sha512": "ddb73c41e907201dfc1e6857ef9e8b5398d1270c7add75c250806585685eab7449a0a78b69456c90415f404ebc5bec145465a79622022a90610ea465a45f775f",
          "sha256": "2ac8e9e9b2d690cdce81a88ff7b8214275aac4d5165154d5cf327be08f603f87",
          "sha1": "89658e9b75408e42ea299dbbaf87537c880880b6",
          "md5": "a602455200a2ddb98128360e9bf516ca"
        }
      ]
    }
  ]
}
