{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-v1.0.0.aar",
          "url": "webview_flutter_android_release-v1.0.0.aar",
          "size": 106264,
          "sha512": "e1d6db1fa81a2253365fd33ffeb51ed5470d9bc5bca9fc935d0fb9334d04fce1d5d5ae58fa41eebcead5398550767d034493b748c4e43cdbabf199b03307657c",
          "sha256": "89371b6957511ced531a863e643b2d70c76007d7cc059070fa12747fef82e35b",
          "sha1": "0cf378b6b4f7818f3ef489c4b8706d06200ec43a",
          "md5": "518aa15d4d89012230a77130707dd6df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-v1.0.0.aar",
          "url": "webview_flutter_android_release-v1.0.0.aar",
          "size": 106264,
          "sha512": "e1d6db1fa81a2253365fd33ffeb51ed5470d9bc5bca9fc935d0fb9334d04fce1d5d5ae58fa41eebcead5398550767d034493b748c4e43cdbabf199b03307657c",
          "sha256": "89371b6957511ced531a863e643b2d70c76007d7cc059070fa12747fef82e35b",
          "sha1": "0cf378b6b4f7818f3ef489c4b8706d06200ec43a",
          "md5": "518aa15d4d89012230a77130707dd6df"
        }
      ]
    }
  ]
}
