{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.britannio.in_app_review",
    "module": "in_app_review_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_review_release-v1.0.2.aar",
          "url": "in_app_review_release-v1.0.2.aar",
          "size": 7895,
          "sha512": "4e52c72c471c1654df6b4e043216ce0b50923a652410f722e03636cc7f856970989d7c5dbf6a323302615803b7a8980595e44e9c5cc09a15f39a907d87016f0c",
          "sha256": "4499dd4f7a48c03b39853b3039c3a805c5bacbd57973803b8a6f0846ccf11446",
          "sha1": "3db0c729750899ed3b30e656d5ec43ce1cc85300",
          "md5": "46f2eefafee4ca28b28c11fd28cf7ac8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_review_release-v1.0.2.aar",
          "url": "in_app_review_release-v1.0.2.aar",
          "size": 7895,
          "sha512": "4e52c72c471c1654df6b4e043216ce0b50923a652410f722e03636cc7f856970989d7c5dbf6a323302615803b7a8980595e44e9c5cc09a15f39a907d87016f0c",
          "sha256": "4499dd4f7a48c03b39853b3039c3a805c5bacbd57973803b8a6f0846ccf11446",
          "sha1": "3db0c729750899ed3b30e656d5ec43ce1cc85300",
          "md5": "46f2eefafee4ca28b28c11fd28cf7ac8"
        }
      ]
    }
  ]
}
