{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_debug",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-30.0.aar",
          "url": "screenshot_prevention_debug-30.0.aar",
          "size": 22694,
          "sha512": "246aca4b4ba003bde7f0bebc86790004fe9dfed955d2958bb20ee3ffa51f39c637457abd70d00b9a1dc21f7ad891746b8fa19afc34c151e07570c416acd67da4",
          "sha256": "d567ccaf70d76b0c189ccfc8e4824d4fdbb4ded416186c8ef5597a27ea5e17a7",
          "sha1": "5c18462c7cf947bc35ac4a2387f12f6d71307fa5",
          "md5": "76e9a69abc56eca02bfac36bc3d04ed4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "30.0"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-30.0.aar",
          "url": "screenshot_prevention_debug-30.0.aar",
          "size": 22694,
          "sha512": "246aca4b4ba003bde7f0bebc86790004fe9dfed955d2958bb20ee3ffa51f39c637457abd70d00b9a1dc21f7ad891746b8fa19afc34c151e07570c416acd67da4",
          "sha256": "d567ccaf70d76b0c189ccfc8e4824d4fdbb4ded416186c8ef5597a27ea5e17a7",
          "sha1": "5c18462c7cf947bc35ac4a2387f12f6d71307fa5",
          "md5": "76e9a69abc56eca02bfac36bc3d04ed4"
        }
      ]
    }
  ]
}
