{
  "formatVersion": "1.1",
  "component": {
    "group": "flutter.plugins.contactsservice.contactsservice",
    "module": "contacts_service_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_debug-26.0.aar",
          "url": "contacts_service_debug-26.0.aar",
          "size": 28861,
          "sha512": "fa8a5e4cda189e475878035dd13215f8afa03635fcc67eabea79f595a739411faeb40e48f8f6e8f1b4fae8da8bc28a9ece6300128fa18ff5fdfa447c0d5d2e97",
          "sha256": "bc56f5f4fc04c84f0b3b442376f2b1bd809cb40ce9a4c502a6ba6f92495d9b75",
          "sha1": "409fcb7a66f579990907e6b4b93ae52b34bc1294",
          "md5": "7fa8d8f4c54f882b8b08d5046df44416"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_debug-26.0.aar",
          "url": "contacts_service_debug-26.0.aar",
          "size": 28861,
          "sha512": "fa8a5e4cda189e475878035dd13215f8afa03635fcc67eabea79f595a739411faeb40e48f8f6e8f1b4fae8da8bc28a9ece6300128fa18ff5fdfa447c0d5d2e97",
          "sha256": "bc56f5f4fc04c84f0b3b442376f2b1bd809cb40ce9a4c502a6ba6f92495d9b75",
          "sha1": "409fcb7a66f579990907e6b4b93ae52b34bc1294",
          "md5": "7fa8d8f4c54f882b8b08d5046df44416"
        }
      ]
    }
  ]
}
