{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.britannio.in_app_review",
    "module": "in_app_review_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_review_debug-v1.0.2.aar",
          "url": "in_app_review_debug-v1.0.2.aar",
          "size": 8300,
          "sha512": "8f472b8dd3dc475fbe07f528fb1c1ec4596ef739cc6306c1b9728c572fa78b9d5f3afd867ed3525821ce722424d6367baff4cba9230b955e5026d85ea0d28a1b",
          "sha256": "89caaa9fb72c4fc3d3e2e8c7455470912d687a62bf47fc0249893b5768d934bd",
          "sha1": "036a8bfc73331f87f167442ec70ee820362b8cc5",
          "md5": "6b0a01060407bf79e9874b63499b55a1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_review_debug-v1.0.2.aar",
          "url": "in_app_review_debug-v1.0.2.aar",
          "size": 8300,
          "sha512": "8f472b8dd3dc475fbe07f528fb1c1ec4596ef739cc6306c1b9728c572fa78b9d5f3afd867ed3525821ce722424d6367baff4cba9230b955e5026d85ea0d28a1b",
          "sha256": "89caaa9fb72c4fc3d3e2e8c7455470912d687a62bf47fc0249893b5768d934bd",
          "sha1": "036a8bfc73331f87f167442ec70ee820362b8cc5",
          "md5": "6b0a01060407bf79e9874b63499b55a1"
        }
      ]
    }
  ]
}
