{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-v1.0.0.aar",
          "url": "core_debug-v1.0.0.aar",
          "size": 37755,
          "sha512": "75620c8cb590b9e926c78204789a5bb34935077c11998d3c365d1adcabf605cbc7c43ee2e14cc89b5aa70069cf2a3f785950df09956ad6827a5e64369f5251bf",
          "sha256": "b826bcf4806aba811d6d39abfcd68aea78119100e117c79ceab5c11ad744ceab",
          "sha1": "12eae4a65e20158a81a999aa4e2b352d1383cb48",
          "md5": "a385c7da758e98bfb1d05cd3552bec29"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_debug",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "v1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-v1.0.0.aar",
          "url": "core_debug-v1.0.0.aar",
          "size": 37755,
          "sha512": "75620c8cb590b9e926c78204789a5bb34935077c11998d3c365d1adcabf605cbc7c43ee2e14cc89b5aa70069cf2a3f785950df09956ad6827a5e64369f5251bf",
          "sha256": "b826bcf4806aba811d6d39abfcd68aea78119100e117c79ceab5c11ad744ceab",
          "sha1": "12eae4a65e20158a81a999aa4e2b352d1383cb48",
          "md5": "a385c7da758e98bfb1d05cd3552bec29"
        }
      ]
    }
  ]
}
