{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_debug-1.0.aar",
          "url": "beacon_debug-1.0.aar",
          "size": 47977,
          "sha512": "a1b81d600222791df1e653b4e177588e33f61b026e141faea754d09f6ee88df03ba4a0862927a2c7545ecfccbbae08f38f67bc7faea5b00101dfb78c7dcabe0e",
          "sha256": "300f78b9607d7828b4fc96d0b78cf986028465321ca51d4f38e282da9700283e",
          "sha1": "5a537999b30e2148adca4c8eb723ae8f272f4db0",
          "md5": "71df91d3f13497ab9dc42ea2c951475e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_debug-1.0.aar",
          "url": "beacon_debug-1.0.aar",
          "size": 47977,
          "sha512": "a1b81d600222791df1e653b4e177588e33f61b026e141faea754d09f6ee88df03ba4a0862927a2c7545ecfccbbae08f38f67bc7faea5b00101dfb78c7dcabe0e",
          "sha256": "300f78b9607d7828b4fc96d0b78cf986028465321ca51d4f38e282da9700283e",
          "sha1": "5a537999b30e2148adca4c8eb723ae8f272f4db0",
          "md5": "71df91d3f13497ab9dc42ea2c951475e"
        }
      ]
    }
  ]
}
