{
  "formatVersion": "1.1",
  "component": {
    "group": "flutter.plugins.contactsservice.contactsservice",
    "module": "contacts_service_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_release-1.0.aar",
          "url": "contacts_service_release-1.0.aar",
          "size": 27443,
          "sha512": "e655d379a59549a69cb97fcd088367f2c939a3374bbc9370e66c35e54df7ec08679699d52c53253ba6554f22061f3b9317517e6d2bd2b01f564b8004ecde3ea4",
          "sha256": "ed82bd318f4e57965eac30d6b23b3a8fe1f4a569cccb26592ba057013b691e90",
          "sha1": "42ff176f76cd94075bb26bbe3680892494b21f57",
          "md5": "d802ad90d99325f20513fa3cec9ca7db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_release-1.0.aar",
          "url": "contacts_service_release-1.0.aar",
          "size": 27443,
          "sha512": "e655d379a59549a69cb97fcd088367f2c939a3374bbc9370e66c35e54df7ec08679699d52c53253ba6554f22061f3b9317517e6d2bd2b01f564b8004ecde3ea4",
          "sha256": "ed82bd318f4e57965eac30d6b23b3a8fe1f4a569cccb26592ba057013b691e90",
          "sha1": "42ff176f76cd94075bb26bbe3680892494b21f57",
          "md5": "d802ad90d99325f20513fa3cec9ca7db"
        }
      ]
    }
  ]
}
