{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xuning.native_font",
    "module": "native_font",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-debug.aar",
          "url": "native_font-26.0-debug.aar",
          "size": 6128,
          "sha512": "892de211a6f5a4622f3a0e89aa3a582581ddcc23202664f3ed766e4f89686a14f51770ceaff5bfa673a3bc8bb92d983b1f14ee1fb5ca006b94143b95f94bc504",
          "sha256": "5269c9ad828bf4eeb96cbe6d24cce374def1c17d29d0ef78222631ef09ee8e1c",
          "sha1": "4581cdc2a65738fbc7ec56ac4bc9ca182627d6b2",
          "md5": "13906ee239bf1754917ecfa05d52a43d"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-debug.aar",
          "url": "native_font-26.0-debug.aar",
          "size": 6128,
          "sha512": "892de211a6f5a4622f3a0e89aa3a582581ddcc23202664f3ed766e4f89686a14f51770ceaff5bfa673a3bc8bb92d983b1f14ee1fb5ca006b94143b95f94bc504",
          "sha256": "5269c9ad828bf4eeb96cbe6d24cce374def1c17d29d0ef78222631ef09ee8e1c",
          "sha1": "4581cdc2a65738fbc7ec56ac4bc9ca182627d6b2",
          "md5": "13906ee239bf1754917ecfa05d52a43d"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-release.aar",
          "url": "native_font-26.0-release.aar",
          "size": 5919,
          "sha512": "e6d81a3cf30329776183c7e25f81243307fe106d2aa67a0c1ca811d10a6b89df6f8c3cf7d816aae147959660b2b93c174ee3ba1fe185cb2bb72b98fa4c81487c",
          "sha256": "f20f72be10c788bdea25b8f3098c040e47d0c06fc2c70a55df454fc670470ec9",
          "sha1": "993f66ee29a38d6e47ba87ea55d692cb3ef620bc",
          "md5": "389dc99055104b8dda9ac20aaddf4ffe"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-release.aar",
          "url": "native_font-26.0-release.aar",
          "size": 5919,
          "sha512": "e6d81a3cf30329776183c7e25f81243307fe106d2aa67a0c1ca811d10a6b89df6f8c3cf7d816aae147959660b2b93c174ee3ba1fe185cb2bb72b98fa4c81487c",
          "sha256": "f20f72be10c788bdea25b8f3098c040e47d0c06fc2c70a55df454fc670470ec9",
          "sha1": "993f66ee29a38d6e47ba87ea55d692cb3ef620bc",
          "md5": "389dc99055104b8dda9ac20aaddf4ffe"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-profile.aar",
          "url": "native_font-26.0-profile.aar",
          "size": 5926,
          "sha512": "9f93cda16eeb556de368fbe7d4cce62aeff31c48d1fb4b2e16f86c15a89b9bdbb9d28a2c9831383aca90618d014984e8f1808c41a3dbf0a354f5f64bd7869aa5",
          "sha256": "3bb718bbb6da64f422a9cb60a52d2f8d52551fad03c88816c95d11fb867cc5fd",
          "sha1": "8c32a51b3407e9abaf7b473b2283b3d7e77d3216",
          "md5": "1fb5d9a792ed384f8f4c96bd5eb088d5"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font-26.0-profile.aar",
          "url": "native_font-26.0-profile.aar",
          "size": 5926,
          "sha512": "9f93cda16eeb556de368fbe7d4cce62aeff31c48d1fb4b2e16f86c15a89b9bdbb9d28a2c9831383aca90618d014984e8f1808c41a3dbf0a354f5f64bd7869aa5",
          "sha256": "3bb718bbb6da64f422a9cb60a52d2f8d52551fad03c88816c95d11fb867cc5fd",
          "sha1": "8c32a51b3407e9abaf7b473b2283b3d7e77d3216",
          "md5": "1fb5d9a792ed384f8f4c96bd5eb088d5"
        }
      ]
    }
  ]
}
