{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-v1.0.0.aar",
          "url": "sqflite_debug-v1.0.0.aar",
          "size": 44369,
          "sha512": "8f10005efce38791c9f4fcce2e53f6621719d6359a6b3e2382ea2466be8bf53d03013274ade6a6c64fbd843dc7764e31470f4e4f0aa0f5a0ad42eb9dd0c37d4a",
          "sha256": "93027480230f24c479cc11ab49aa7ee561ab575a26fd0acd5e27985f31eb7c1c",
          "sha1": "b37ce571006da1e91ad8a215799a058e268fc045",
          "md5": "224d6d1c142c5e7271d659cf762fafc6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-v1.0.0.aar",
          "url": "sqflite_debug-v1.0.0.aar",
          "size": 44369,
          "sha512": "8f10005efce38791c9f4fcce2e53f6621719d6359a6b3e2382ea2466be8bf53d03013274ade6a6c64fbd843dc7764e31470f4e4f0aa0f5a0ad42eb9dd0c37d4a",
          "sha256": "93027480230f24c479cc11ab49aa7ee561ab575a26fd0acd5e27985f31eb7c1c",
          "sha1": "b37ce571006da1e91ad8a215799a058e268fc045",
          "md5": "224d6d1c142c5e7271d659cf762fafc6"
        }
      ]
    }
  ]
}
