{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_debug",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.spencerccf.app_settings",
          "module": "app_settings_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_debug",
          "version": {
            "requires": "v1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.0.4.aar",
          "url": "flutter_debug-v1.0.4.aar",
          "size": 24824856,
          "sha512": "538d0c7ca2e5447180c0c49a7bea6a7e5bc68fd95e1989e712c8ee6e013f904004403ee8b3918fa5025993b7fc2fdf062a3c6d72d62c5631d2b11c46f767297e",
          "sha256": "1477828b6449629d43cf4deaafbb62b007cce9f32fba190d5bb03cd0f25eb042",
          "sha1": "4ece89370af7bc1b0926b36e861ca0017a9db06c",
          "md5": "3c5405d828b00b857c4dadcc691afaa8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.spencerccf.app_settings",
          "module": "app_settings_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_debug",
          "version": {
            "requires": "v1.0.4"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_debug",
          "version": {
            "requires": "v1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-v1.0.4.aar",
          "url": "flutter_debug-v1.0.4.aar",
          "size": 24824856,
          "sha512": "538d0c7ca2e5447180c0c49a7bea6a7e5bc68fd95e1989e712c8ee6e013f904004403ee8b3918fa5025993b7fc2fdf062a3c6d72d62c5631d2b11c46f767297e",
          "sha256": "1477828b6449629d43cf4deaafbb62b007cce9f32fba190d5bb03cd0f25eb042",
          "sha1": "4ece89370af7bc1b0926b36e861ca0017a9db06c",
          "md5": "3c5405d828b00b857c4dadcc691afaa8"
        }
      ]
    }
  ]
}
