{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xuning.native_font",
    "module": "native_font_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_debug-v1.0.2.aar",
          "url": "native_font_debug-v1.0.2.aar",
          "size": 6178,
          "sha512": "b4fcfa3a88a9a6bffba22d8649a2a276b1e9ca4db1780a6c9249938c39180a63ae02ffc59da6d1f9b6c738c9f318243155e3764a773ba03a684a691907644723",
          "sha256": "07b816ef72ebe15509ad54de02f26fdc058118eca9dce27bec56e6a54cb627cf",
          "sha1": "38ab386097653a279171c6f882ab90c8f874d4fd",
          "md5": "4cda544ac3ad4d6eb2c8c078ff761b2e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_debug-v1.0.2.aar",
          "url": "native_font_debug-v1.0.2.aar",
          "size": 6178,
          "sha512": "b4fcfa3a88a9a6bffba22d8649a2a276b1e9ca4db1780a6c9249938c39180a63ae02ffc59da6d1f9b6c738c9f318243155e3764a773ba03a684a691907644723",
          "sha256": "07b816ef72ebe15509ad54de02f26fdc058118eca9dce27bec56e6a54cb627cf",
          "sha1": "38ab386097653a279171c6f882ab90c8f874d4fd",
          "md5": "4cda544ac3ad4d6eb2c8c078ff761b2e"
        }
      ]
    }
  ]
}
