{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-v1.0.0.aar",
          "url": "core_release-v1.0.0.aar",
          "size": 37036,
          "sha512": "361a1fb5102779c3322c849d719afed96f0302683205718a7455210e6dfe996f5e03098b898ff259ae37962cddda8bbcf1448e1307f69c75d87994b9bf6a1214",
          "sha256": "8be5d9065767063b8edfcc7b5801cf2c1a9b084e647e59203637067e15b90a6b",
          "sha1": "ba0022d42c41edb81d211cfcf0a2796e6d161fad",
          "md5": "ddbc8f4740c0d7910673ec507a50366b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_release",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "v1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-v1.0.0.aar",
          "url": "core_release-v1.0.0.aar",
          "size": 37036,
          "sha512": "361a1fb5102779c3322c849d719afed96f0302683205718a7455210e6dfe996f5e03098b898ff259ae37962cddda8bbcf1448e1307f69c75d87994b9bf6a1214",
          "sha256": "8be5d9065767063b8edfcc7b5801cf2c1a9b084e647e59203637067e15b90a6b",
          "sha1": "ba0022d42c41edb81d211cfcf0a2796e6d161fad",
          "md5": "ddbc8f4740c0d7910673ec507a50366b"
        }
      ]
    }
  ]
}
