{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-v1.0.0.aar",
          "url": "permission_handler_android_debug-v1.0.0.aar",
          "size": 27228,
          "sha512": "f3363cd3f0b9625b3d317bf4d6c878acfcfd5301399e453d57217f687153797fc87df39c4c93f6db83d50a6df28c36334523d48845079b509469699971fe61d3",
          "sha256": "35798f99a27b84ea9847b08e1836b363e7473c14cc4e773af2a09d21fe59f5c6",
          "sha1": "bc6993d18f072a5053dc3832a44eb4887b5a5129",
          "md5": "a65590542b1361d3d5f84c5f2e3fbc40"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-v1.0.0.aar",
          "url": "permission_handler_android_debug-v1.0.0.aar",
          "size": 27228,
          "sha512": "f3363cd3f0b9625b3d317bf4d6c878acfcfd5301399e453d57217f687153797fc87df39c4c93f6db83d50a6df28c36334523d48845079b509469699971fe61d3",
          "sha256": "35798f99a27b84ea9847b08e1836b363e7473c14cc4e773af2a09d21fe59f5c6",
          "sha1": "bc6993d18f072a5053dc3832a44eb4887b5a5129",
          "md5": "a65590542b1361d3d5f84c5f2e3fbc40"
        }
      ]
    }
  ]
}
