{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wongpiwat.trust_location",
    "module": "trust_location_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_release-30.0.aar",
          "url": "trust_location_release-30.0.aar",
          "size": 34636,
          "sha512": "60c810235cd7586d511da0ac39d83d11ebec7e19edd26e6f009c5fc9ab438cf80f38d6bc239b78a96ac5d5604336f1ac7b13e6bb245d171aab9b0a87c168d0d1",
          "sha256": "8e474a22a7d74aeea4acd80315e6f253650d1eacbc2d733b1ce77733b55dab4c",
          "sha1": "05eedaaeeaf2d9abc1557f0cf6c811570a46cbbb",
          "md5": "e444dcb9e9feccc8b069a028acb53941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_release-30.0.aar",
          "url": "trust_location_release-30.0.aar",
          "size": 34636,
          "sha512": "60c810235cd7586d511da0ac39d83d11ebec7e19edd26e6f009c5fc9ab438cf80f38d6bc239b78a96ac5d5604336f1ac7b13e6bb245d171aab9b0a87c168d0d1",
          "sha256": "8e474a22a7d74aeea4acd80315e6f253650d1eacbc2d733b1ce77733b55dab4c",
          "sha1": "05eedaaeeaf2d9abc1557f0cf6c811570a46cbbb",
          "md5": "e444dcb9e9feccc8b069a028acb53941"
        }
      ]
    }
  ]
}
