{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_release",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-26.0.aar",
          "url": "system_uptime_release-26.0.aar",
          "size": 5400,
          "sha512": "fff6930907da9c9e5294e9e34d8e25bb1b7af306541d2e12c426444d567492deb0f6a03f8712b89b24d855debc3b5d78a41cf742b621404d53ef72e89668fed1",
          "sha256": "ad068ea250a4c20eede08f76593f8e91b5f6fa87be69af59532672a1540d19f1",
          "sha1": "92b95d31c95fbc7b5cd8409bf2cb9cfb863b5c9b",
          "md5": "8f6f4960def86bcb188de30d4450d6ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-26.0.aar",
          "url": "system_uptime_release-26.0.aar",
          "size": 5400,
          "sha512": "fff6930907da9c9e5294e9e34d8e25bb1b7af306541d2e12c426444d567492deb0f6a03f8712b89b24d855debc3b5d78a41cf742b621404d53ef72e89668fed1",
          "sha256": "ad068ea250a4c20eede08f76593f8e91b5f6fa87be69af59532672a1540d19f1",
          "sha1": "92b95d31c95fbc7b5cd8409bf2cb9cfb863b5c9b",
          "md5": "8f6f4960def86bcb188de30d4450d6ad"
        }
      ]
    }
  ]
}
