{
  "formatVersion": "1.1",
  "component": {
    "group": "com.julienvignali.phone_number",
    "module": "phone_number_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "phone_number_release-v1.0.0.aar",
          "url": "phone_number_release-v1.0.0.aar",
          "size": 9432,
          "sha512": "5096a4a8443d1725a11aa062917cf6322b029b8288748c093a89201594229cdcd2b94fd86e6063b2da16f5404a4fd02a7b352545ff2131e68073b899be133c0b",
          "sha256": "b66116c7c296970373a1dcf8b4a752780f7cfd2a55460831f2d645b40bfda118",
          "sha1": "754e048b3c69a60f87ec76a06bceab228d8a7d3f",
          "md5": "471c534d641cb36359389c7f24c94c1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.10"
          }
        }
      ],
      "files": [
        {
          "name": "phone_number_release-v1.0.0.aar",
          "url": "phone_number_release-v1.0.0.aar",
          "size": 9432,
          "sha512": "5096a4a8443d1725a11aa062917cf6322b029b8288748c093a89201594229cdcd2b94fd86e6063b2da16f5404a4fd02a7b352545ff2131e68073b899be133c0b",
          "sha256": "b66116c7c296970373a1dcf8b4a752780f7cfd2a55460831f2d645b40bfda118",
          "sha1": "754e048b3c69a60f87ec76a06bceab228d8a7d3f",
          "md5": "471c534d641cb36359389c7f24c94c1d"
        }
      ]
    }
  ]
}
