{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_debug",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-30.0.aar",
          "url": "system_uptime_debug-30.0.aar",
          "size": 5616,
          "sha512": "9ebc843e29e7443d737121b39b9f83f65e5431c996de451040a176631520bcf93c869798d067d0b978b0b6e2a3d8f5d68c86eed34996838332b8bbc162faee3f",
          "sha256": "572e51348c70cefc35d91601cbfb4d9843da06164681846c730a4bc07506234a",
          "sha1": "a814e3d981c12ebb5a11caee827db23590f5cbaf",
          "md5": "25a4cfac66c963143ad88b771a4f574a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-30.0.aar",
          "url": "system_uptime_debug-30.0.aar",
          "size": 5616,
          "sha512": "9ebc843e29e7443d737121b39b9f83f65e5431c996de451040a176631520bcf93c869798d067d0b978b0b6e2a3d8f5d68c86eed34996838332b8bbc162faee3f",
          "sha256": "572e51348c70cefc35d91601cbfb4d9843da06164681846c730a4bc07506234a",
          "sha1": "a814e3d981c12ebb5a11caee827db23590f5cbaf",
          "md5": "25a4cfac66c963143ad88b771a4f574a"
        }
      ]
    }
  ]
}
