{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-30.0.aar",
          "url": "permission_handler_android_release-30.0.aar",
          "size": 25972,
          "sha512": "faf313fcf8f30ee0b9479dfb07a3468ed387ee6cb3ae6abc2b465f7e9ace815045a9baf5f0c7d027ccc21d31f8a1eb5d86952d43514133afba7d003106a0fe8d",
          "sha256": "f9a2ff25aa5e9c7ad4910691db7e41ff5db0d0a44aa3c251d79b5ce2a8f29417",
          "sha1": "eaefbfd52cf406fdb754bf853d7aea58c638c01b",
          "md5": "b3509e34e5658c7d7227ebfb85d449a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-30.0.aar",
          "url": "permission_handler_android_release-30.0.aar",
          "size": 25972,
          "sha512": "faf313fcf8f30ee0b9479dfb07a3468ed387ee6cb3ae6abc2b465f7e9ace815045a9baf5f0c7d027ccc21d31f8a1eb5d86952d43514133afba7d003106a0fe8d",
          "sha256": "f9a2ff25aa5e9c7ad4910691db7e41ff5db0d0a44aa3c251d79b5ce2a8f29417",
          "sha1": "eaefbfd52cf406fdb754bf853d7aea58c638c01b",
          "md5": "b3509e34e5658c7d7227ebfb85d449a4"
        }
      ]
    }
  ]
}
