{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-26.0.aar",
          "url": "core_debug-26.0.aar",
          "size": 37448,
          "sha512": "55493066237081dfd5732576d971b3b869b134a6fb582b7807dce76fb4fc85d43a2707c5c4def2774e04c617787e9466d95bc605bf92c46dbafcc441586804d7",
          "sha256": "2957cc427809b25efbabda9d3edfc920be41dca971426fd4305d14ed690a74ef",
          "sha1": "5db1f7f127d87ac3cd50d2de68e22b086b6d3587",
          "md5": "b69bc0077fb0774b5d660b72947ced32"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_debug-26.0.aar",
          "url": "core_debug-26.0.aar",
          "size": 37448,
          "sha512": "55493066237081dfd5732576d971b3b869b134a6fb582b7807dce76fb4fc85d43a2707c5c4def2774e04c617787e9466d95bc605bf92c46dbafcc441586804d7",
          "sha256": "2957cc427809b25efbabda9d3edfc920be41dca971426fd4305d14ed690a74ef",
          "sha1": "5db1f7f127d87ac3cd50d2de68e22b086b6d3587",
          "md5": "b69bc0077fb0774b5d660b72947ced32"
        }
      ]
    }
  ]
}
