{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mathrawk.libphonenumber",
    "module": "libphonenumber_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber_debug-26.0.aar",
          "url": "libphonenumber_debug-26.0.aar",
          "size": 7518,
          "sha512": "5fa2741bffe855719a26a53b920d7b9ff6d4d077eedb6531d3ee1f98d556a1e008f38b87d95896a5b117d058c98f129eba55faf151b3c0c34f58fed9cb1f5bcb",
          "sha256": "555c8894b7943aaba2b7b5395c91909020e94f3bf6e84191d7fe2ec91c99a216",
          "sha1": "3f20cad716eac856ce291462d9a442cf084457a6",
          "md5": "2988b5b0083c9fb8728ed753292f5f2a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber_debug-26.0.aar",
          "url": "libphonenumber_debug-26.0.aar",
          "size": 7518,
          "sha512": "5fa2741bffe855719a26a53b920d7b9ff6d4d077eedb6531d3ee1f98d556a1e008f38b87d95896a5b117d058c98f129eba55faf151b3c0c34f58fed9cb1f5bcb",
          "sha256": "555c8894b7943aaba2b7b5395c91909020e94f3bf6e84191d7fe2ec91c99a216",
          "sha1": "3f20cad716eac856ce291462d9a442cf084457a6",
          "md5": "2988b5b0083c9fb8728ed753292f5f2a"
        }
      ]
    }
  ]
}
