{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_release",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_release-v1.0.4.aar",
          "url": "screenshot_prevention_release-v1.0.4.aar",
          "size": 58363,
          "sha512": "0ed084289d3fae76028d3d670c646086a46aa0c5f2bc6b04fcd537a511e8717b25f978ca02c854660770f657acec817eb635d2ad29149ebd03eba53277f64786",
          "sha256": "836567793c3e847cda19cc971feaf12c19e2b17fad2c58ca3200010e12d056b4",
          "sha1": "a5025da4a799fe527d9bee9483b00f09a9a9d7af",
          "md5": "3b8c794a712afcd0267ac4474b19f117"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "v1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_release-v1.0.4.aar",
          "url": "screenshot_prevention_release-v1.0.4.aar",
          "size": 58363,
          "sha512": "0ed084289d3fae76028d3d670c646086a46aa0c5f2bc6b04fcd537a511e8717b25f978ca02c854660770f657acec817eb635d2ad29149ebd03eba53277f64786",
          "sha256": "836567793c3e847cda19cc971feaf12c19e2b17fad2c58ca3200010e12d056b4",
          "sha1": "a5025da4a799fe527d9bee9483b00f09a9a9d7af",
          "md5": "3b8c794a712afcd0267ac4474b19f117"
        }
      ]
    }
  ]
}
