{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-v1.0.2.aar",
          "url": "webview_flutter_android_debug-v1.0.2.aar",
          "size": 112920,
          "sha512": "4a7f5f733f6664337d6bc10aa178c0d59114684bb65e2eeef905c0580addaef1df05b8f265a91fcdf080b4566847fd50799202efe04e349db3377bbf4085e742",
          "sha256": "4ef7af97c60f4ec0a4d01b82f7546af65ed1bc674a4931cc7b3672fd577a90cc",
          "sha1": "a7f9023d047febcb86fcbdb7a6987c71bd38dbce",
          "md5": "e0ccdb95ac932099d77c41a84cf61e80"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-v1.0.2.aar",
          "url": "webview_flutter_android_debug-v1.0.2.aar",
          "size": 112920,
          "sha512": "4a7f5f733f6664337d6bc10aa178c0d59114684bb65e2eeef905c0580addaef1df05b8f265a91fcdf080b4566847fd50799202efe04e349db3377bbf4085e742",
          "sha256": "4ef7af97c60f4ec0a4d01b82f7546af65ed1bc674a4931cc7b3672fd577a90cc",
          "sha1": "a7f9023d047febcb86fcbdb7a6987c71bd38dbce",
          "md5": "e0ccdb95ac932099d77c41a84cf61e80"
        }
      ]
    }
  ]
}
