{
  "formatVersion": "1.1",
  "component": {
    "group": "com.julienvignali.phone_number",
    "module": "phone_number_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "phone_number_debug-v1.0.2.aar",
          "url": "phone_number_debug-v1.0.2.aar",
          "size": 9865,
          "sha512": "4c55bf357ed36194fb5dbaea39795aa197687840b401a6065f9a4733b0ba1aaba8a8a6a8a5530530eda504f5622d21423cab7c3bf92b8162ed4223100fcca94d",
          "sha256": "e98bfa39eb1930eed19fb3107812ca95c234b21778d57caee91f9d1783364174",
          "sha1": "5bb3e82a2676bd774a698e15a57aa411a8bde701",
          "md5": "5cc64ad65da5c58837b00d626b301ea0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.10"
          }
        }
      ],
      "files": [
        {
          "name": "phone_number_debug-v1.0.2.aar",
          "url": "phone_number_debug-v1.0.2.aar",
          "size": 9865,
          "sha512": "4c55bf357ed36194fb5dbaea39795aa197687840b401a6065f9a4733b0ba1aaba8a8a6a8a5530530eda504f5622d21423cab7c3bf92b8162ed4223100fcca94d",
          "sha256": "e98bfa39eb1930eed19fb3107812ca95c234b21778d57caee91f9d1783364174",
          "sha1": "5bb3e82a2676bd774a698e15a57aa411a8bde701",
          "md5": "5cc64ad65da5c58837b00d626b301ea0"
        }
      ]
    }
  ]
}
