{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-v1.0.0.aar",
          "url": "system_uptime_debug-v1.0.0.aar",
          "size": 5687,
          "sha512": "1a591b9a865083b68931f9e75af6e01aea5808cad27bb1aeab61ebc67da04065f91bc9f82d5a44067af3ac25b98bd6a47a4c9ce353e96b7245167cf154364dcf",
          "sha256": "10f63af71182c04493c3df0dfbe03654a27f1f57d3258e0a72d827fac1b74eb4",
          "sha1": "da825489b97ccd4a4849c4f141dd7c818d699f2f",
          "md5": "b31b23c2f1b4f3beace0476749add021"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-v1.0.0.aar",
          "url": "system_uptime_debug-v1.0.0.aar",
          "size": 5687,
          "sha512": "1a591b9a865083b68931f9e75af6e01aea5808cad27bb1aeab61ebc67da04065f91bc9f82d5a44067af3ac25b98bd6a47a4c9ce353e96b7245167cf154364dcf",
          "sha256": "10f63af71182c04493c3df0dfbe03654a27f1f57d3258e0a72d827fac1b74eb4",
          "sha1": "da825489b97ccd4a4849c4f141dd7c818d699f2f",
          "md5": "b31b23c2f1b4f3beace0476749add021"
        }
      ]
    }
  ]
}
