{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_profile-1.0.aar",
          "url": "beacon_profile-1.0.aar",
          "size": 46358,
          "sha512": "a1882e43cdfbdfc54734aacde370189c018765547d56fa06cbddfe9fd7dcc6e2d645ffdfecca30c69643bfd93646d395121dfd46f852e9232377114ecdc8a377",
          "sha256": "41363ad934c80913a8d86cf3e51c43e463cf860f8e045e058985c84f6a20a152",
          "sha1": "febed2248ea65778ff1d88f697221530d2115fe7",
          "md5": "de8892122a82db0d21e1b1736626d331"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_profile-1.0.aar",
          "url": "beacon_profile-1.0.aar",
          "size": 46358,
          "sha512": "a1882e43cdfbdfc54734aacde370189c018765547d56fa06cbddfe9fd7dcc6e2d645ffdfecca30c69643bfd93646d395121dfd46f852e9232377114ecdc8a377",
          "sha256": "41363ad934c80913a8d86cf3e51c43e463cf860f8e045e058985c84f6a20a152",
          "sha1": "febed2248ea65778ff1d88f697221530d2115fe7",
          "md5": "de8892122a82db0d21e1b1736626d331"
        }
      ]
    }
  ]
}
