{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "core_profile-1.0.aar",
          "url": "core_profile-1.0.aar",
          "size": 36798,
          "sha512": "cecdfe9984101e98342d0b65dab6a163ba5e7fc9f7d679157c909077071b484db0d6d28735fc98942c97569309b51bdfc04039c085e9f3d9185c326faf6493ed",
          "sha256": "a8bfa7b73e907b10cf6487817bae046007694b17d24c186500a9132877e68c9e",
          "sha1": "47b33c5308d96a10c00e80faec14146e477432dd",
          "md5": "020440f7dd09fbff8ea704fe8fc8a8f7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_profile-1.0.aar",
          "url": "core_profile-1.0.aar",
          "size": 36798,
          "sha512": "cecdfe9984101e98342d0b65dab6a163ba5e7fc9f7d679157c909077071b484db0d6d28735fc98942c97569309b51bdfc04039c085e9f3d9185c326faf6493ed",
          "sha256": "a8bfa7b73e907b10cf6487817bae046007694b17d24c186500a9132877e68c9e",
          "sha1": "47b33c5308d96a10c00e80faec14146e477432dd",
          "md5": "020440f7dd09fbff8ea704fe8fc8a8f7"
        }
      ]
    }
  ]
}
