{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "26.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-26.0.aar",
          "url": "flutter_profile-26.0.aar",
          "size": 22978,
          "sha512": "89701699ba488bb676e3ec317ba6bb6afb3c477b1d53d51a1f33aef5603ad9aeeb936ddc2822bcb4d50fcd90eb3330e45abc4e4b8822b42480918a72cb9383a1",
          "sha256": "f2c804a8ef06d42987766a6cfc9423d333ace722553cdfc82ce695471a01688e",
          "sha1": "9022e37c7da81532e6076d1b2bd48187ab63a5b9",
          "md5": "76302e03da89b5f0d33d56f3d712ac52"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "26.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-26.0.aar",
          "url": "flutter_profile-26.0.aar",
          "size": 22978,
          "sha512": "89701699ba488bb676e3ec317ba6bb6afb3c477b1d53d51a1f33aef5603ad9aeeb936ddc2822bcb4d50fcd90eb3330e45abc4e4b8822b42480918a72cb9383a1",
          "sha256": "f2c804a8ef06d42987766a6cfc9423d333ace722553cdfc82ce695471a01688e",
          "sha1": "9022e37c7da81532e6076d1b2bd48187ab63a5b9",
          "md5": "76302e03da89b5f0d33d56f3d712ac52"
        }
      ]
    }
  ]
}
