{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xuning.native_font",
    "module": "native_font_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_debug-26.0.aar",
          "url": "native_font_debug-26.0.aar",
          "size": 6128,
          "sha512": "892de211a6f5a4622f3a0e89aa3a582581ddcc23202664f3ed766e4f89686a14f51770ceaff5bfa673a3bc8bb92d983b1f14ee1fb5ca006b94143b95f94bc504",
          "sha256": "5269c9ad828bf4eeb96cbe6d24cce374def1c17d29d0ef78222631ef09ee8e1c",
          "sha1": "4581cdc2a65738fbc7ec56ac4bc9ca182627d6b2",
          "md5": "13906ee239bf1754917ecfa05d52a43d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "native_font_debug-26.0.aar",
          "url": "native_font_debug-26.0.aar",
          "size": 6128,
          "sha512": "892de211a6f5a4622f3a0e89aa3a582581ddcc23202664f3ed766e4f89686a14f51770ceaff5bfa673a3bc8bb92d983b1f14ee1fb5ca006b94143b95f94bc504",
          "sha256": "5269c9ad828bf4eeb96cbe6d24cce374def1c17d29d0ef78222631ef09ee8e1c",
          "sha1": "4581cdc2a65738fbc7ec56ac4bc9ca182627d6b2",
          "md5": "13906ee239bf1754917ecfa05d52a43d"
        }
      ]
    }
  ]
}
