{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-v1.0.0.aar",
          "url": "url_launcher_android_debug-v1.0.0.aar",
          "size": 15738,
          "sha512": "1be3244781a55fe4caf0017f64c2965bb3a7d42bb5cc28970c622a2fb9104c1bddb0f65345d270667e509b519a6e2e1aa99ddc5c68cb1658267fa3d1f7527df9",
          "sha256": "2e5072564d87605be03a09921c36450b11007000631ef61f44f57372689b6631",
          "sha1": "8d952a84213392e39ae055320d3cb3a59f95e364",
          "md5": "3cf2a2628e1a1c6a63e4ae0ac2478774"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-v1.0.0.aar",
          "url": "url_launcher_android_debug-v1.0.0.aar",
          "size": 15738,
          "sha512": "1be3244781a55fe4caf0017f64c2965bb3a7d42bb5cc28970c622a2fb9104c1bddb0f65345d270667e509b519a6e2e1aa99ddc5c68cb1658267fa3d1f7527df9",
          "sha256": "2e5072564d87605be03a09921c36450b11007000631ef61f44f57372689b6631",
          "sha1": "8d952a84213392e39ae055320d3cb3a59f95e364",
          "md5": "3cf2a2628e1a1c6a63e4ae0ac2478774"
        }
      ]
    }
  ]
}
