{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_release",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.0.2.aar",
          "url": "flutter_release-v1.0.2.aar",
          "size": 16400150,
          "sha512": "b9fca5ef4115a2e5a57e09b5449c79b6f63239e51d73044eb66d3df16d59e6beecfcf3843e3330148a090ef51c74a411f0e274534b4af0e8e40fc7dcd4134463",
          "sha256": "ec436730b742f152f80f86cc331a2c3788158b9abdbe9df4b9956249da3a00bf",
          "sha1": "3585f5cf6ff9edbe9b1eaf705763ac6116c4bd0c",
          "md5": "e95147d6274ceda3587a363010c0ede5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.britannio.in_app_review",
          "module": "in_app_review_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_release",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-v1.0.2.aar",
          "url": "flutter_release-v1.0.2.aar",
          "size": 16400150,
          "sha512": "b9fca5ef4115a2e5a57e09b5449c79b6f63239e51d73044eb66d3df16d59e6beecfcf3843e3330148a090ef51c74a411f0e274534b4af0e8e40fc7dcd4134463",
          "sha256": "ec436730b742f152f80f86cc331a2c3788158b9abdbe9df4b9956249da3a00bf",
          "sha1": "3585f5cf6ff9edbe9b1eaf705763ac6116c4bd0c",
          "md5": "e95147d6274ceda3587a363010c0ede5"
        }
      ]
    }
  ]
}
