{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-26.0.aar",
          "url": "connectivity_plus_debug-26.0.aar",
          "size": 9324,
          "sha512": "20e9628a71da7bb541ece7882dbb03f7dbd6e16f3d7b8759e4547a64aaeeb77481fd3d179a4dbb824657f51ef0edb76fb829efec85c2ff78176bfb9ccc9509b3",
          "sha256": "daef0e6aa947aafe404c8bb982c305d3d2f39978203ad831bc204af543d784b0",
          "sha1": "1c43acaaff9a3bd6251ed13d825f854319a22980",
          "md5": "f13567fd299c61c3f1ce5746e00a4dd1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-26.0.aar",
          "url": "connectivity_plus_debug-26.0.aar",
          "size": 9324,
          "sha512": "20e9628a71da7bb541ece7882dbb03f7dbd6e16f3d7b8759e4547a64aaeeb77481fd3d179a4dbb824657f51ef0edb76fb829efec85c2ff78176bfb9ccc9509b3",
          "sha256": "daef0e6aa947aafe404c8bb982c305d3d2f39978203ad831bc204af543d784b0",
          "sha1": "1c43acaaff9a3bd6251ed13d825f854319a22980",
          "md5": "f13567fd299c61c3f1ce5746e00a4dd1"
        }
      ]
    }
  ]
}
