{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.wallet_suppression",
    "module": "wallet_suppression_release",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_release-26.0.aar",
          "url": "wallet_suppression_release-26.0.aar",
          "size": 6931,
          "sha512": "8271c5de9ef98eca753ec0ab0d45f4734bea0e545b5fbd58d18ff21652ca0461b1039654b56b95f00fa872858304df930488e0904b39f78d6299170e8c15ae3f",
          "sha256": "2863908610055f1f76c949f1c312002f56cc7b544eb4720326b802a3f252a3c8",
          "sha1": "4045b6c23c926ac8867872f2ad5834c13bac937c",
          "md5": "91dced198e7e5c8d0c3e1ab93628e78a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_release-26.0.aar",
          "url": "wallet_suppression_release-26.0.aar",
          "size": 6931,
          "sha512": "8271c5de9ef98eca753ec0ab0d45f4734bea0e545b5fbd58d18ff21652ca0461b1039654b56b95f00fa872858304df930488e0904b39f78d6299170e8c15ae3f",
          "sha256": "2863908610055f1f76c949f1c312002f56cc7b544eb4720326b802a3f252a3c8",
          "sha1": "4045b6c23c926ac8867872f2ad5834c13bac937c",
          "md5": "91dced198e7e5c8d0c3e1ab93628e78a"
        }
      ]
    }
  ]
}
