{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-1.0.aar",
          "url": "safe_device_release-1.0.aar",
          "size": 21448,
          "sha512": "f8a82a3ece1b78a5e9221b6c5af363cf9a82de78f6f94fcbdb54291ab2606baada1e034302543a2144b2be4b76341f99c31027ed8fb1de2c60f2eef6d17c78c5",
          "sha256": "f43c61b829385e76e54f4b6575f7c1c6068db9aa4c2920f2b0629a9d2542650a",
          "sha1": "740303d174780aa71c37ed2556a2c4724ae2c361",
          "md5": "79ac3cb3cf2cf244fe7eaf20953e637a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-1.0.aar",
          "url": "safe_device_release-1.0.aar",
          "size": 21448,
          "sha512": "f8a82a3ece1b78a5e9221b6c5af363cf9a82de78f6f94fcbdb54291ab2606baada1e034302543a2144b2be4b76341f99c31027ed8fb1de2c60f2eef6d17c78c5",
          "sha256": "f43c61b829385e76e54f4b6575f7c1c6068db9aa4c2920f2b0629a9d2542650a",
          "sha1": "740303d174780aa71c37ed2556a2c4724ae2c361",
          "md5": "79ac3cb3cf2cf244fe7eaf20953e637a"
        }
      ]
    }
  ]
}
