{
  "formatVersion": "1.1",
  "component": {
    "group": "flutter.plugins.contactsservice.contactsservice",
    "module": "contacts_service",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-debug.aar",
          "url": "contacts_service-1.0-debug.aar",
          "size": 28861,
          "sha512": "fa8a5e4cda189e475878035dd13215f8afa03635fcc67eabea79f595a739411faeb40e48f8f6e8f1b4fae8da8bc28a9ece6300128fa18ff5fdfa447c0d5d2e97",
          "sha256": "bc56f5f4fc04c84f0b3b442376f2b1bd809cb40ce9a4c502a6ba6f92495d9b75",
          "sha1": "409fcb7a66f579990907e6b4b93ae52b34bc1294",
          "md5": "7fa8d8f4c54f882b8b08d5046df44416"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-debug.aar",
          "url": "contacts_service-1.0-debug.aar",
          "size": 28861,
          "sha512": "fa8a5e4cda189e475878035dd13215f8afa03635fcc67eabea79f595a739411faeb40e48f8f6e8f1b4fae8da8bc28a9ece6300128fa18ff5fdfa447c0d5d2e97",
          "sha256": "bc56f5f4fc04c84f0b3b442376f2b1bd809cb40ce9a4c502a6ba6f92495d9b75",
          "sha1": "409fcb7a66f579990907e6b4b93ae52b34bc1294",
          "md5": "7fa8d8f4c54f882b8b08d5046df44416"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-release.aar",
          "url": "contacts_service-1.0-release.aar",
          "size": 27443,
          "sha512": "e655d379a59549a69cb97fcd088367f2c939a3374bbc9370e66c35e54df7ec08679699d52c53253ba6554f22061f3b9317517e6d2bd2b01f564b8004ecde3ea4",
          "sha256": "ed82bd318f4e57965eac30d6b23b3a8fe1f4a569cccb26592ba057013b691e90",
          "sha1": "42ff176f76cd94075bb26bbe3680892494b21f57",
          "md5": "d802ad90d99325f20513fa3cec9ca7db"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-release.aar",
          "url": "contacts_service-1.0-release.aar",
          "size": 27443,
          "sha512": "e655d379a59549a69cb97fcd088367f2c939a3374bbc9370e66c35e54df7ec08679699d52c53253ba6554f22061f3b9317517e6d2bd2b01f564b8004ecde3ea4",
          "sha256": "ed82bd318f4e57965eac30d6b23b3a8fe1f4a569cccb26592ba057013b691e90",
          "sha1": "42ff176f76cd94075bb26bbe3680892494b21f57",
          "md5": "d802ad90d99325f20513fa3cec9ca7db"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-profile.aar",
          "url": "contacts_service-1.0-profile.aar",
          "size": 27438,
          "sha512": "69ef7688f21d9dd814b7c3b44d1ec2ca89adf4dda473ab88d7211ea5b3375c99e167c7ab504162118e4a421afdc2bd34828e03933f321f406f70433005575166",
          "sha256": "29fcc2e7506898b24fc8f2917943d10c655d81b1e16dc457908197a78dee1e77",
          "sha1": "906ac3496e3262de2e94a3b764298418b48e7344",
          "md5": "474be9003ba6c6c3c06897ede3f8a50f"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service-1.0-profile.aar",
          "url": "contacts_service-1.0-profile.aar",
          "size": 27438,
          "sha512": "69ef7688f21d9dd814b7c3b44d1ec2ca89adf4dda473ab88d7211ea5b3375c99e167c7ab504162118e4a421afdc2bd34828e03933f321f406f70433005575166",
          "sha256": "29fcc2e7506898b24fc8f2917943d10c655d81b1e16dc457908197a78dee1e77",
          "sha1": "906ac3496e3262de2e94a3b764298418b48e7344",
          "md5": "474be9003ba6c6c3c06897ede3f8a50f"
        }
      ]
    }
  ]
}
