{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-debug.aar",
          "url": "permission_handler_android-26.0-debug.aar",
          "size": 26142,
          "sha512": "14a6af95acba36e9c13002aec3bdf398067829eddf2d8be752290d3417447b34f0df42810eb4411d843f1bae91d3dd66e1cd44b7f37efe1aeac6b99da11b24ff",
          "sha256": "d8e125a09a25fce275a3620078661ac5bafeb1baf50d3e443a15d4be8ff18025",
          "sha1": "f5ac8725a04f8a85cffcee58218c65a73302f582",
          "md5": "2454daf98c9ceb33942e1deb82230e8d"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-debug.aar",
          "url": "permission_handler_android-26.0-debug.aar",
          "size": 26142,
          "sha512": "14a6af95acba36e9c13002aec3bdf398067829eddf2d8be752290d3417447b34f0df42810eb4411d843f1bae91d3dd66e1cd44b7f37efe1aeac6b99da11b24ff",
          "sha256": "d8e125a09a25fce275a3620078661ac5bafeb1baf50d3e443a15d4be8ff18025",
          "sha1": "f5ac8725a04f8a85cffcee58218c65a73302f582",
          "md5": "2454daf98c9ceb33942e1deb82230e8d"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-release.aar",
          "url": "permission_handler_android-26.0-release.aar",
          "size": 25026,
          "sha512": "03a00b88c016faad9f70439ce72820334e4c24335d9e2ab3f6d4ed986a2ec27e3b2242aa94bd85d87b332e8bb681d00fb0070646de31047689ef87c7259612f0",
          "sha256": "1ef3f19b365eff0b694b2d2562e1e3c254cbaa88e1aeb5be98f0312af65300e1",
          "sha1": "9c5ab00d5a7ad1fcd9e0db994a601e22b4ae864b",
          "md5": "3216578c5b4f713cfaaef4e150929596"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-release.aar",
          "url": "permission_handler_android-26.0-release.aar",
          "size": 25026,
          "sha512": "03a00b88c016faad9f70439ce72820334e4c24335d9e2ab3f6d4ed986a2ec27e3b2242aa94bd85d87b332e8bb681d00fb0070646de31047689ef87c7259612f0",
          "sha256": "1ef3f19b365eff0b694b2d2562e1e3c254cbaa88e1aeb5be98f0312af65300e1",
          "sha1": "9c5ab00d5a7ad1fcd9e0db994a601e22b4ae864b",
          "md5": "3216578c5b4f713cfaaef4e150929596"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-profile.aar",
          "url": "permission_handler_android-26.0-profile.aar",
          "size": 25028,
          "sha512": "3a94b64e3a55a6cbba2cb0395393308f307cd657c69f8fd15aab4938fc1d9bba03a6daf9973d31a7c11f836464433908f99c1685ebc66eb472c9b4b80fbdaab8",
          "sha256": "de5d4aa41e1f45b6f348c6fe5c33a98a5fce9e12a2a9b1a7ec98de150ec950df",
          "sha1": "1ba6df7077342965d0dd8f805b3048bc1e993c3a",
          "md5": "38db04be27b150021b44ec3762f77403"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android-26.0-profile.aar",
          "url": "permission_handler_android-26.0-profile.aar",
          "size": 25028,
          "sha512": "3a94b64e3a55a6cbba2cb0395393308f307cd657c69f8fd15aab4938fc1d9bba03a6daf9973d31a7c11f836464433908f99c1685ebc66eb472c9b4b80fbdaab8",
          "sha256": "de5d4aa41e1f45b6f348c6fe5c33a98a5fce9e12a2a9b1a7ec98de150ec950df",
          "sha1": "1ba6df7077342965d0dd8f805b3048bc1e993c3a",
          "md5": "38db04be27b150021b44ec3762f77403"
        }
      ]
    }
  ]
}
