{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.wallet_suppression",
    "module": "wallet_suppression_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_debug-v1.0.0.aar",
          "url": "wallet_suppression_debug-v1.0.0.aar",
          "size": 7259,
          "sha512": "c666a8fd61cee386c2e2d714ae9a5fe104509db6a42d6ae42ee8062344eaf8ee3770aa6ec57bbeeab7858d43be16b4206617894ba3d0f58088e729dd88777453",
          "sha256": "ce8c4e48f8c9e0d42e591c2e44bd737f97c1dafdd393d667d02b5114d4099d9e",
          "sha1": "590c57c3a68e0daa90d3f974ba8ac8f241c85165",
          "md5": "2760c302de8535bd3dce11f98d5918ba"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_debug-v1.0.0.aar",
          "url": "wallet_suppression_debug-v1.0.0.aar",
          "size": 7259,
          "sha512": "c666a8fd61cee386c2e2d714ae9a5fe104509db6a42d6ae42ee8062344eaf8ee3770aa6ec57bbeeab7858d43be16b4206617894ba3d0f58088e729dd88777453",
          "sha256": "ce8c4e48f8c9e0d42e591c2e44bd737f97c1dafdd393d667d02b5114d4099d9e",
          "sha1": "590c57c3a68e0daa90d3f974ba8ac8f241c85165",
          "md5": "2760c302de8535bd3dce11f98d5918ba"
        }
      ]
    }
  ]
}
