{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device_release",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-v1.0.4.aar",
          "url": "safe_device_release-v1.0.4.aar",
          "size": 75621,
          "sha512": "4b2f91c9cd6111ae9eed16d82ecaa1ead587e77378bfd0a0de3eebf7ab2e1b6a5d14f4dc3ac80fc6777abbc3ce5c298a7014dc5606fd0175bc8d102ebbf3794e",
          "sha256": "5afcbbf3817d5f2743a8e8d7ea8c228212b725681c3fb533d6317a8e096279eb",
          "sha1": "f314021a071fdaa01de1b970fc8541fb26eef7ff",
          "md5": "4ebfa7c0715b53194c289655578267e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-v1.0.4.aar",
          "url": "safe_device_release-v1.0.4.aar",
          "size": 75621,
          "sha512": "4b2f91c9cd6111ae9eed16d82ecaa1ead587e77378bfd0a0de3eebf7ab2e1b6a5d14f4dc3ac80fc6777abbc3ce5c298a7014dc5606fd0175bc8d102ebbf3794e",
          "sha256": "5afcbbf3817d5f2743a8e8d7ea8c228212b725681c3fb533d6317a8e096279eb",
          "sha1": "f314021a071fdaa01de1b970fc8541fb26eef7ff",
          "md5": "4ebfa7c0715b53194c289655578267e2"
        }
      ]
    }
  ]
}
