{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-v1.0.2.aar",
          "url": "url_launcher_android_debug-v1.0.2.aar",
          "size": 22454,
          "sha512": "e126cd0ee2c8a39f3587d3e03918c3a033415bd7f9559654bf830e75b5d4ccf597beaab58d38574e2ba442c9acd7eb5cf2a4d6215aeacd287834c0581d078f65",
          "sha256": "55188feb0e6375c38ae84e88422dabaf43a362fb42944787b20329f644d96383",
          "sha1": "9401eb69e958f7279114d2b2d89a65aa044c44b4",
          "md5": "4d25e7e4130feda294d6f62dd0cf2097"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-v1.0.2.aar",
          "url": "url_launcher_android_debug-v1.0.2.aar",
          "size": 22454,
          "sha512": "e126cd0ee2c8a39f3587d3e03918c3a033415bd7f9559654bf830e75b5d4ccf597beaab58d38574e2ba442c9acd7eb5cf2a4d6215aeacd287834c0581d078f65",
          "sha256": "55188feb0e6375c38ae84e88422dabaf43a362fb42944787b20329f644d96383",
          "sha1": "9401eb69e958f7279114d2b2d89a65aa044c44b4",
          "md5": "4d25e7e4130feda294d6f62dd0cf2097"
        }
      ]
    }
  ]
}
