{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-1.0.aar",
          "url": "beacon_release-1.0.aar",
          "size": 46569,
          "sha512": "54900e2723488dbe5c9b7817e8565916f01a8bff27eedb83e9d91581a5bacefd7624e512b40422a5ecbb72521e2902828ea274724c23c1594a048f28e3612f52",
          "sha256": "cb82a0a5062a0ea9b84de889c9a30300317accd23e5743683de37ae091fd1f10",
          "sha1": "572bb6f7f8de013661a6671c33d9db2e66e00407",
          "md5": "5a038bf1218d42fdac8845a044679219"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon_release-1.0.aar",
          "url": "beacon_release-1.0.aar",
          "size": 46569,
          "sha512": "54900e2723488dbe5c9b7817e8565916f01a8bff27eedb83e9d91581a5bacefd7624e512b40422a5ecbb72521e2902828ea274724c23c1594a048f28e3612f52",
          "sha256": "cb82a0a5062a0ea9b84de889c9a30300317accd23e5743683de37ae091fd1f10",
          "sha1": "572bb6f7f8de013661a6671c33d9db2e66e00407",
          "md5": "5a038bf1218d42fdac8845a044679219"
        }
      ]
    }
  ]
}
