{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-v1.0.0.aar",
          "url": "url_launcher_android_release-v1.0.0.aar",
          "size": 15102,
          "sha512": "21f380139d064fb93f90e0c425d19ee271a5ae8a7e06a762ebb3929a641dd032857ef1c48fe755847751af5fa9676314f83581a5b24db69a9283a7f3694ac2d0",
          "sha256": "6c42ba93f4f6e142f0bbec33a75f05e5cbcf6e292530cf422f4df6af4ddff5a6",
          "sha1": "654a21d0c7e350dfa334419aa1e57eeaa97960ff",
          "md5": "7759d01b244784dbe82bf76cc02f6b11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-v1.0.0.aar",
          "url": "url_launcher_android_release-v1.0.0.aar",
          "size": 15102,
          "sha512": "21f380139d064fb93f90e0c425d19ee271a5ae8a7e06a762ebb3929a641dd032857ef1c48fe755847751af5fa9676314f83581a5b24db69a9283a7f3694ac2d0",
          "sha256": "6c42ba93f4f6e142f0bbec33a75f05e5cbcf6e292530cf422f4df6af4ddff5a6",
          "sha1": "654a21d0c7e350dfa334419aa1e57eeaa97960ff",
          "md5": "7759d01b244784dbe82bf76cc02f6b11"
        }
      ]
    }
  ]
}
