{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.wallet_suppression",
    "module": "wallet_suppression_release",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_release-v1.0.4.aar",
          "url": "wallet_suppression_release-v1.0.4.aar",
          "size": 7025,
          "sha512": "f4fd0fbcba87e23295748098d7f83d3ad2825c642f409112877fda3c421cb42d19cee26364bb16cad2e49953feeedb6bd61c570af40e2e98485819a8dc31cbf1",
          "sha256": "587c84ea34b55cacbe5a0ae872ae513fb7358daa7ea7a495c0cfc46ce0d099bb",
          "sha1": "bf923fa6b7249ddcf81fcf6e790567d8030fa541",
          "md5": "9f15e60a32e6d1b9078b2d8d5e469100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_release-v1.0.4.aar",
          "url": "wallet_suppression_release-v1.0.4.aar",
          "size": 7025,
          "sha512": "f4fd0fbcba87e23295748098d7f83d3ad2825c642f409112877fda3c421cb42d19cee26364bb16cad2e49953feeedb6bd61c570af40e2e98485819a8dc31cbf1",
          "sha256": "587c84ea34b55cacbe5a0ae872ae513fb7358daa7ea7a495c0cfc46ce0d099bb",
          "sha1": "bf923fa6b7249ddcf81fcf6e790567d8030fa541",
          "md5": "9f15e60a32e6d1b9078b2d8d5e469100"
        }
      ]
    }
  ]
}
