{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_debug",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-26.0.aar",
          "url": "system_uptime_debug-26.0.aar",
          "size": 5583,
          "sha512": "4d69f46e2d3967690b107c5bfb91be125c8c4115c1aff25e08ccb6237741a2e61c95b1a100b1062d7291f28452c5dbfc9ecea9b16de1b3d0d179b2c4d2f40fc6",
          "sha256": "9cf698d097996ad2014ceb0cb5f29873d15b3a1f88c9d6eace8ffb344bb3d843",
          "sha1": "b8e2b054823d809a7fb5427d6724c22c9233fb0b",
          "md5": "100acedf827f24288327882caf859a8b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_debug-26.0.aar",
          "url": "system_uptime_debug-26.0.aar",
          "size": 5583,
          "sha512": "4d69f46e2d3967690b107c5bfb91be125c8c4115c1aff25e08ccb6237741a2e61c95b1a100b1062d7291f28452c5dbfc9ecea9b16de1b3d0d179b2c4d2f40fc6",
          "sha256": "9cf698d097996ad2014ceb0cb5f29873d15b3a1f88c9d6eace8ffb344bb3d843",
          "sha1": "b8e2b054823d809a7fb5427d6724c22c9233fb0b",
          "md5": "100acedf827f24288327882caf859a8b"
        }
      ]
    }
  ]
}
