{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-v1.0.2.aar",
          "url": "system_uptime_release-v1.0.2.aar",
          "size": 5506,
          "sha512": "2bfb8aa8f6eb7226ab2a638d703226a8ee32a9cb6c357bb2f2341cf6854a77c70435020a63532c9105044d776c0a315485ebf6d88c53406486c935a4758e2031",
          "sha256": "206947132dbc898822ce8817b7a2353a2a7de750ced4e9c6f9ebb8432d68d830",
          "sha1": "a221bbcde894b04d38ec10c177e7c83be41b9e2d",
          "md5": "2dc39840ecddc2e525c883915eccc562"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_release-v1.0.2.aar",
          "url": "system_uptime_release-v1.0.2.aar",
          "size": 5506,
          "sha512": "2bfb8aa8f6eb7226ab2a638d703226a8ee32a9cb6c357bb2f2341cf6854a77c70435020a63532c9105044d776c0a315485ebf6d88c53406486c935a4758e2031",
          "sha256": "206947132dbc898822ce8817b7a2353a2a7de750ced4e9c6f9ebb8432d68d830",
          "sha1": "a221bbcde894b04d38ec10c177e7c83be41b9e2d",
          "md5": "2dc39840ecddc2e525c883915eccc562"
        }
      ]
    }
  ]
}
