{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 112834,
          "sha512": "4a6352bde281bbfacf116339dc9c55d58dc696f94c5238c517ac11f5e569e1707a473d6d26e3db3b586ae4f85fe18223dd9476fc9547470a8364d97648e1481b",
          "sha256": "820972e5dffcdc4af17ca58496878f3f96cd4ec6a2108f58b990a79fff62870d",
          "sha1": "7d262d6647ce6efc8a5c085153b28bbfa34bc77e",
          "md5": "dd1f06d9f0c4d422222cfc735b2e2937"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 112834,
          "sha512": "4a6352bde281bbfacf116339dc9c55d58dc696f94c5238c517ac11f5e569e1707a473d6d26e3db3b586ae4f85fe18223dd9476fc9547470a8364d97648e1481b",
          "sha256": "820972e5dffcdc4af17ca58496878f3f96cd4ec6a2108f58b990a79fff62870d",
          "sha1": "7d262d6647ce6efc8a5c085153b28bbfa34bc77e",
          "md5": "dd1f06d9f0c4d422222cfc735b2e2937"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 106180,
          "sha512": "ff58197d3245e0146d95b3e69ee3f2090184d11ac6b690a8b77660eefc40dbe2ccdf53fcc42e34807475254f2ed3d4b37edd623b596a7c64656fab4c5f830dbd",
          "sha256": "ffa6fa7c21d068c7e7c31c90815168077dd7f8a4cf4d2939b857fc64b4d51ce5",
          "sha1": "b261edb687a96b97e54fc1b6e39b94929909c3cc",
          "md5": "88d804d707cecc9d926b298957de5f7c"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 106180,
          "sha512": "ff58197d3245e0146d95b3e69ee3f2090184d11ac6b690a8b77660eefc40dbe2ccdf53fcc42e34807475254f2ed3d4b37edd623b596a7c64656fab4c5f830dbd",
          "sha256": "ffa6fa7c21d068c7e7c31c90815168077dd7f8a4cf4d2939b857fc64b4d51ce5",
          "sha1": "b261edb687a96b97e54fc1b6e39b94929909c3cc",
          "md5": "88d804d707cecc9d926b298957de5f7c"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 106177,
          "sha512": "69b3221b5b20aaafa78b512cc298d6ea7f7826cb16a756148e8e7ca2c0441f33d5ea5b44dcd4706f4347bd3071e8bf79ee8b41cd2752ca44362dd66bd5481eba",
          "sha256": "57215a614761885ae556df7ff4b32c09204f9b649f231e5cedee912506801ec9",
          "sha1": "3b49782c57ffa35a5e437f8e86bc2ffb55f1255b",
          "md5": "24e8656f3a86e70f831f6f1a1133c2c4"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 106177,
          "sha512": "69b3221b5b20aaafa78b512cc298d6ea7f7826cb16a756148e8e7ca2c0441f33d5ea5b44dcd4706f4347bd3071e8bf79ee8b41cd2752ca44362dd66bd5481eba",
          "sha256": "57215a614761885ae556df7ff4b32c09204f9b649f231e5cedee912506801ec9",
          "sha1": "3b49782c57ffa35a5e437f8e86bc2ffb55f1255b",
          "md5": "24e8656f3a86e70f831f6f1a1133c2c4"
        }
      ]
    }
  ]
}
