{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wongpiwat.trust_location",
    "module": "trust_location",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-debug.aar",
          "url": "trust_location-1.0-debug.aar",
          "size": 35833,
          "sha512": "f5b130a363a343c530423452591882a465fd2378e3098c74598c5dc408e549fa8350efc9b5f5fc5046bf3c3baa852112685ed1f36ddb1eb19b1baf586ca4bfed",
          "sha256": "daf77f37940803dae97dfe5ef1709791df517890bc35fd231ca22e8831ea942e",
          "sha1": "cf6820a8a7495fb0555386c55bd7188948a69c5c",
          "md5": "dfaff55037c30413c50a4c4608b4899c"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-debug.aar",
          "url": "trust_location-1.0-debug.aar",
          "size": 35833,
          "sha512": "f5b130a363a343c530423452591882a465fd2378e3098c74598c5dc408e549fa8350efc9b5f5fc5046bf3c3baa852112685ed1f36ddb1eb19b1baf586ca4bfed",
          "sha256": "daf77f37940803dae97dfe5ef1709791df517890bc35fd231ca22e8831ea942e",
          "sha1": "cf6820a8a7495fb0555386c55bd7188948a69c5c",
          "md5": "dfaff55037c30413c50a4c4608b4899c"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-release.aar",
          "url": "trust_location-1.0-release.aar",
          "size": 34636,
          "sha512": "60c810235cd7586d511da0ac39d83d11ebec7e19edd26e6f009c5fc9ab438cf80f38d6bc239b78a96ac5d5604336f1ac7b13e6bb245d171aab9b0a87c168d0d1",
          "sha256": "8e474a22a7d74aeea4acd80315e6f253650d1eacbc2d733b1ce77733b55dab4c",
          "sha1": "05eedaaeeaf2d9abc1557f0cf6c811570a46cbbb",
          "md5": "e444dcb9e9feccc8b069a028acb53941"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-release.aar",
          "url": "trust_location-1.0-release.aar",
          "size": 34636,
          "sha512": "60c810235cd7586d511da0ac39d83d11ebec7e19edd26e6f009c5fc9ab438cf80f38d6bc239b78a96ac5d5604336f1ac7b13e6bb245d171aab9b0a87c168d0d1",
          "sha256": "8e474a22a7d74aeea4acd80315e6f253650d1eacbc2d733b1ce77733b55dab4c",
          "sha1": "05eedaaeeaf2d9abc1557f0cf6c811570a46cbbb",
          "md5": "e444dcb9e9feccc8b069a028acb53941"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-profile.aar",
          "url": "trust_location-1.0-profile.aar",
          "size": 34637,
          "sha512": "1c0bc8a6a3b979ae0cf0722c3dc84ad98026261de6124186ec1a06355de87b777bc83d03e7e09a4f17a3c95b74eeeb995fc49034fa7acc7cc1d35de37496ba72",
          "sha256": "5fc14a664074ba3d9fa8e4a59c04f1766ae01c9e48cc49ee94dd63636aebd7ba",
          "sha1": "350612f9148cc139f20dc140f98870271e580d64",
          "md5": "696f5c2886890b965eae148f56c25bf3"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location-1.0-profile.aar",
          "url": "trust_location-1.0-profile.aar",
          "size": 34637,
          "sha512": "1c0bc8a6a3b979ae0cf0722c3dc84ad98026261de6124186ec1a06355de87b777bc83d03e7e09a4f17a3c95b74eeeb995fc49034fa7acc7cc1d35de37496ba72",
          "sha256": "5fc14a664074ba3d9fa8e4a59c04f1766ae01c9e48cc49ee94dd63636aebd7ba",
          "sha1": "350612f9148cc139f20dc140f98870271e580d64",
          "md5": "696f5c2886890b965eae148f56c25bf3"
        }
      ]
    }
  ]
}
