{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.appsettings",
    "module": "app_settings_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_profile-26.0.aar",
          "url": "app_settings_profile-26.0.aar",
          "size": 8174,
          "sha512": "15b22b6df6cbc37ed6a8c9a3787eeb952b91308e12a7d49ffdb671710ad18a19513b96812c4ebe295daf1df93b2bb42fef797141a8b944833b909093ab92002d",
          "sha256": "154395a083c961fb1a8f23cc76b10a51c7d1b6dd461854c0febd3f8a7da35109",
          "sha1": "a91d45b8a63a53b5601f4e8ee400cb83673e343f",
          "md5": "d29b2e13ca34390fda57fe3ead5c8688"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_profile-26.0.aar",
          "url": "app_settings_profile-26.0.aar",
          "size": 8174,
          "sha512": "15b22b6df6cbc37ed6a8c9a3787eeb952b91308e12a7d49ffdb671710ad18a19513b96812c4ebe295daf1df93b2bb42fef797141a8b944833b909093ab92002d",
          "sha256": "154395a083c961fb1a8f23cc76b10a51c7d1b6dd461854c0febd3f8a7da35109",
          "sha1": "a91d45b8a63a53b5601f4e8ee400cb83673e343f",
          "md5": "d29b2e13ca34390fda57fe3ead5c8688"
        }
      ]
    }
  ]
}
