{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_release",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-26.0.aar",
          "url": "core_release-26.0.aar",
          "size": 36778,
          "sha512": "f3574e575653a2103b5218235b8b0f28a75557145292364e1b576eed7e6c5a3116310dc793efefa22022c2b629c8d9575e7f507c605d8123308a920c353a4740",
          "sha256": "cb8f66f03d16e1d16c933ba2c3d3ccd873ab031dda4911e68bf4959712e49dc0",
          "sha1": "5242e55fda6e53bd40224d9714e95816be82b00f",
          "md5": "70d966d87155ccae7bf59393489671d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device",
          "version": {
            "requires": "26.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font",
          "version": {
            "requires": "26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-26.0.aar",
          "url": "core_release-26.0.aar",
          "size": 36778,
          "sha512": "f3574e575653a2103b5218235b8b0f28a75557145292364e1b576eed7e6c5a3116310dc793efefa22022c2b629c8d9575e7f507c605d8123308a920c353a4740",
          "sha256": "cb8f66f03d16e1d16c933ba2c3d3ccd873ab031dda4911e68bf4959712e49dc0",
          "sha1": "5242e55fda6e53bd40224d9714e95816be82b00f",
          "md5": "70d966d87155ccae7bf59393489671d5"
        }
      ]
    }
  ]
}
