{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.system_uptime",
    "module": "system_uptime_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_profile-26.0.aar",
          "url": "system_uptime_profile-26.0.aar",
          "size": 5399,
          "sha512": "6c3845ab0cddff726f00e897acb58de651f32e8fda0f82d980b6593147bd70c7edd9db3f7ac8553039fc4c0b03ce7e723a0b013f2e7eba5d02faae3d9c0ba19f",
          "sha256": "bc15c424eca5ce0821ac8c767b01cf3f87ff1087174ea3afa2ef7cc6b08b15c6",
          "sha1": "e7191c9df53831018842d080bdc530b45a663a28",
          "md5": "e233ce2d960e32acdb3d57baf6e8eeb7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "system_uptime_profile-26.0.aar",
          "url": "system_uptime_profile-26.0.aar",
          "size": 5399,
          "sha512": "6c3845ab0cddff726f00e897acb58de651f32e8fda0f82d980b6593147bd70c7edd9db3f7ac8553039fc4c0b03ce7e723a0b013f2e7eba5d02faae3d9c0ba19f",
          "sha256": "bc15c424eca5ce0821ac8c767b01cf3f87ff1087174ea3afa2ef7cc6b08b15c6",
          "sha1": "e7191c9df53831018842d080bdc530b45a663a28",
          "md5": "e233ce2d960e32acdb3d57baf6e8eeb7"
        }
      ]
    }
  ]
}
