{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.0.aar",
          "url": "sqflite_profile-1.0.aar",
          "size": 42246,
          "sha512": "95b470a2967ffa74ee281b15baf3314af3dfc1e55df29c3ac9fea656ac80e5d96fa6c1c6b1447b790f2fdf23cab1ce8f949c062bce01def92c7d2a39e445c249",
          "sha256": "bbda9332e845e3d684ba3e5f266347c332bb9a985a7917b9045029f28ddac896",
          "sha1": "9a988584333c5d6b5c8efc76ca18b6f0341daf0c",
          "md5": "615bdb70ade0607c9cfea8ac411b6d97"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.0.aar",
          "url": "sqflite_profile-1.0.aar",
          "size": 42246,
          "sha512": "95b470a2967ffa74ee281b15baf3314af3dfc1e55df29c3ac9fea656ac80e5d96fa6c1c6b1447b790f2fdf23cab1ce8f949c062bce01def92c7d2a39e445c249",
          "sha256": "bbda9332e845e3d684ba3e5f266347c332bb9a985a7917b9045029f28ddac896",
          "sha1": "9a988584333c5d6b5c8efc76ca18b6f0341daf0c",
          "md5": "615bdb70ade0607c9cfea8ac411b6d97"
        }
      ]
    }
  ]
}
