{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26142,
          "sha512": "14a6af95acba36e9c13002aec3bdf398067829eddf2d8be752290d3417447b34f0df42810eb4411d843f1bae91d3dd66e1cd44b7f37efe1aeac6b99da11b24ff",
          "sha256": "d8e125a09a25fce275a3620078661ac5bafeb1baf50d3e443a15d4be8ff18025",
          "sha1": "f5ac8725a04f8a85cffcee58218c65a73302f582",
          "md5": "2454daf98c9ceb33942e1deb82230e8d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26142,
          "sha512": "14a6af95acba36e9c13002aec3bdf398067829eddf2d8be752290d3417447b34f0df42810eb4411d843f1bae91d3dd66e1cd44b7f37efe1aeac6b99da11b24ff",
          "sha256": "d8e125a09a25fce275a3620078661ac5bafeb1baf50d3e443a15d4be8ff18025",
          "sha1": "f5ac8725a04f8a85cffcee58218c65a73302f582",
          "md5": "2454daf98c9ceb33942e1deb82230e8d"
        }
      ]
    }
  ]
}
