{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.beacon",
    "module": "beacon",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-debug.aar",
          "url": "beacon-1.0-debug.aar",
          "size": 47977,
          "sha512": "a1b81d600222791df1e653b4e177588e33f61b026e141faea754d09f6ee88df03ba4a0862927a2c7545ecfccbbae08f38f67bc7faea5b00101dfb78c7dcabe0e",
          "sha256": "300f78b9607d7828b4fc96d0b78cf986028465321ca51d4f38e282da9700283e",
          "sha1": "5a537999b30e2148adca4c8eb723ae8f272f4db0",
          "md5": "71df91d3f13497ab9dc42ea2c951475e"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-debug.aar",
          "url": "beacon-1.0-debug.aar",
          "size": 47977,
          "sha512": "a1b81d600222791df1e653b4e177588e33f61b026e141faea754d09f6ee88df03ba4a0862927a2c7545ecfccbbae08f38f67bc7faea5b00101dfb78c7dcabe0e",
          "sha256": "300f78b9607d7828b4fc96d0b78cf986028465321ca51d4f38e282da9700283e",
          "sha1": "5a537999b30e2148adca4c8eb723ae8f272f4db0",
          "md5": "71df91d3f13497ab9dc42ea2c951475e"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-release.aar",
          "url": "beacon-1.0-release.aar",
          "size": 46569,
          "sha512": "54900e2723488dbe5c9b7817e8565916f01a8bff27eedb83e9d91581a5bacefd7624e512b40422a5ecbb72521e2902828ea274724c23c1594a048f28e3612f52",
          "sha256": "cb82a0a5062a0ea9b84de889c9a30300317accd23e5743683de37ae091fd1f10",
          "sha1": "572bb6f7f8de013661a6671c33d9db2e66e00407",
          "md5": "5a038bf1218d42fdac8845a044679219"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-release.aar",
          "url": "beacon-1.0-release.aar",
          "size": 46569,
          "sha512": "54900e2723488dbe5c9b7817e8565916f01a8bff27eedb83e9d91581a5bacefd7624e512b40422a5ecbb72521e2902828ea274724c23c1594a048f28e3612f52",
          "sha256": "cb82a0a5062a0ea9b84de889c9a30300317accd23e5743683de37ae091fd1f10",
          "sha1": "572bb6f7f8de013661a6671c33d9db2e66e00407",
          "md5": "5a038bf1218d42fdac8845a044679219"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-profile.aar",
          "url": "beacon-1.0-profile.aar",
          "size": 46358,
          "sha512": "a1882e43cdfbdfc54734aacde370189c018765547d56fa06cbddfe9fd7dcc6e2d645ffdfecca30c69643bfd93646d395121dfd46f852e9232377114ecdc8a377",
          "sha256": "41363ad934c80913a8d86cf3e51c43e463cf860f8e045e058985c84f6a20a152",
          "sha1": "febed2248ea65778ff1d88f697221530d2115fe7",
          "md5": "de8892122a82db0d21e1b1736626d331"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.kontakt.mvn",
          "module": "sdk",
          "version": {
            "requires": "5.0.25"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "beacon-1.0-profile.aar",
          "url": "beacon-1.0-profile.aar",
          "size": 46358,
          "sha512": "a1882e43cdfbdfc54734aacde370189c018765547d56fa06cbddfe9fd7dcc6e2d645ffdfecca30c69643bfd93646d395121dfd46f852e9232377114ecdc8a377",
          "sha256": "41363ad934c80913a8d86cf3e51c43e463cf860f8e045e058985c84f6a20a152",
          "sha1": "febed2248ea65778ff1d88f697221530d2115fe7",
          "md5": "de8892122a82db0d21e1b1736626d331"
        }
      ]
    }
  ]
}
