{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wongpiwat.trust_location",
    "module": "trust_location_release",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_release-v1.0.0.aar",
          "url": "trust_location_release-v1.0.0.aar",
          "size": 34704,
          "sha512": "d1a7f0160d69b61fa6955039e131412faa6236b595c7592c7ba6d8d08ed5883488c6e627374dcb75b0ff36ed16cff0d1e43d33bcf77d352de4d6014ce7732637",
          "sha256": "e267136736d705c7098dc3c07d2fcbaadfc0e838c4fbb1526e31389f1541c5ad",
          "sha1": "d363975e8389a679f3fce1f53ef69d210568ccde",
          "md5": "0d515cec3f84039d30a092cf3328fb8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "trust_location_release-v1.0.0.aar",
          "url": "trust_location_release-v1.0.0.aar",
          "size": 34704,
          "sha512": "d1a7f0160d69b61fa6955039e131412faa6236b595c7592c7ba6d8d08ed5883488c6e627374dcb75b0ff36ed16cff0d1e43d33bcf77d352de4d6014ce7732637",
          "sha256": "e267136736d705c7098dc3c07d2fcbaadfc0e838c4fbb1526e31389f1541c5ad",
          "sha1": "d363975e8389a679f3fce1f53ef69d210568ccde",
          "md5": "0d515cec3f84039d30a092cf3328fb8d"
        }
      ]
    }
  ]
}
