{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25026,
          "sha512": "03a00b88c016faad9f70439ce72820334e4c24335d9e2ab3f6d4ed986a2ec27e3b2242aa94bd85d87b332e8bb681d00fb0070646de31047689ef87c7259612f0",
          "sha256": "1ef3f19b365eff0b694b2d2562e1e3c254cbaa88e1aeb5be98f0312af65300e1",
          "sha1": "9c5ab00d5a7ad1fcd9e0db994a601e22b4ae864b",
          "md5": "3216578c5b4f713cfaaef4e150929596"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25026,
          "sha512": "03a00b88c016faad9f70439ce72820334e4c24335d9e2ab3f6d4ed986a2ec27e3b2242aa94bd85d87b332e8bb681d00fb0070646de31047689ef87c7259612f0",
          "sha256": "1ef3f19b365eff0b694b2d2562e1e3c254cbaa88e1aeb5be98f0312af65300e1",
          "sha1": "9c5ab00d5a7ad1fcd9e0db994a601e22b4ae864b",
          "md5": "3216578c5b4f713cfaaef4e150929596"
        }
      ]
    }
  ]
}
