{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_debug",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.0.aar",
          "url": "screenshot_prevention_debug-v1.0.0.aar",
          "size": 31990,
          "sha512": "964ce1086f6a4904acc5c4d1f43dbf07ad3fb3766a6c2d1bd8abf92099d2926aec8f486a84c659f63db4c792b14499336e52bef317e18406ef2075e5ed371f0d",
          "sha256": "61df033dcb4dcad4ea91de7db785d61f1af13827d05b20ec49f92f976ad0719e",
          "sha1": "09a6c380cb10dea3d513343ffdd3be7ab34f5e6c",
          "md5": "ce9d4f4ae0c7626020d9ba32404842ed"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.0.aar",
          "url": "screenshot_prevention_debug-v1.0.0.aar",
          "size": 31990,
          "sha512": "964ce1086f6a4904acc5c4d1f43dbf07ad3fb3766a6c2d1bd8abf92099d2926aec8f486a84c659f63db4c792b14499336e52bef317e18406ef2075e5ed371f0d",
          "sha256": "61df033dcb4dcad4ea91de7db785d61f1af13827d05b20ec49f92f976ad0719e",
          "sha1": "09a6c380cb10dea3d513343ffdd3be7ab34f5e6c",
          "md5": "ce9d4f4ae0c7626020d9ba32404842ed"
        }
      ]
    }
  ]
}
