{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spencerccf.app_settings",
    "module": "app_settings_release",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-v1.0.4.aar",
          "url": "app_settings_release-v1.0.4.aar",
          "size": 8946,
          "sha512": "2cfc368697ab7ea70192797a0ac8e703f1b2f8ba364828f39426e3588fe0eea6cbe0304f5c9fbb096cf186cb64ac54f1682b4a14a5668fccc8491d4373fc19e3",
          "sha256": "eb45b80a03453f2113ee661a2f7f7ba99b972c07e15ab82e0e399bc7c16171c9",
          "sha1": "6e228d2c31d072916dfc57d6675f5b606869314b",
          "md5": "c944018a4c3e80c35b592b20d35543bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_release-v1.0.4.aar",
          "url": "app_settings_release-v1.0.4.aar",
          "size": 8946,
          "sha512": "2cfc368697ab7ea70192797a0ac8e703f1b2f8ba364828f39426e3588fe0eea6cbe0304f5c9fbb096cf186cb64ac54f1682b4a14a5668fccc8491d4373fc19e3",
          "sha256": "eb45b80a03453f2113ee661a2f7f7ba99b972c07e15ab82e0e399bc7c16171c9",
          "sha1": "6e228d2c31d072916dfc57d6675f5b606869314b",
          "md5": "c944018a4c3e80c35b592b20d35543bf"
        }
      ]
    }
  ]
}
