{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-v1.0.2.aar",
          "url": "sqflite_release-v1.0.2.aar",
          "size": 45174,
          "sha512": "bfac3cf1a12495a0ec11b746809ecc60f960946eae1774ccd9fe4368017c05ce141ff4e329ee7d2302bab1ee615f37b9e8c02933e5293ef4c4fca91b5b796653",
          "sha256": "da461f2801d671bd22f941e894ec3fb22ec05265c4b2616d12a9fd19ff1e1973",
          "sha1": "885fa1e8e8874a7faa4c5f9fa0cde42b31516460",
          "md5": "8b3a248631ac1bccb7e248215905781f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-v1.0.2.aar",
          "url": "sqflite_release-v1.0.2.aar",
          "size": 45174,
          "sha512": "bfac3cf1a12495a0ec11b746809ecc60f960946eae1774ccd9fe4368017c05ce141ff4e329ee7d2302bab1ee615f37b9e8c02933e5293ef4c4fca91b5b796653",
          "sha256": "da461f2801d671bd22f941e894ec3fb22ec05265c4b2616d12a9fd19ff1e1973",
          "sha1": "885fa1e8e8874a7faa4c5f9fa0cde42b31516460",
          "md5": "8b3a248631ac1bccb7e248215905781f"
        }
      ]
    }
  ]
}
