{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.sdk",
    "module": "flutter_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_release",
          "version": {
            "requires": "30.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-30.0.aar",
          "url": "flutter_release-30.0.aar",
          "size": 16414659,
          "sha512": "f142a29a523dafa973ceb01bdbd50ff5cc5e0530e8d66119c7fd5c7d783be53cc2618775e728ddfcb0d55a25b32e2416e4b03e19502840983e611acbee4c3ea8",
          "sha256": "ae346a0702a1d84f2232adca808022f31e3f173c87315da90a0b5e33fa146e6d",
          "sha1": "d5ba4da01bf0097de246b518a2957bd8474d2e5a",
          "md5": "be411103a527e59a2668fbff611819d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.beacon",
          "module": "beacon_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.wallet_suppression",
          "module": "wallet_suppression_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.example.system_uptime",
          "module": "system_uptime_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "flutter.plugins.contactsservice.contactsservice",
          "module": "contacts_service_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.tixngo.screenshot_prevention",
          "module": "screenshot_prevention_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_release",
          "version": {
            "requires": "30.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-30.0.aar",
          "url": "flutter_release-30.0.aar",
          "size": 16414659,
          "sha512": "f142a29a523dafa973ceb01bdbd50ff5cc5e0530e8d66119c7fd5c7d783be53cc2618775e728ddfcb0d55a25b32e2416e4b03e19502840983e611acbee4c3ea8",
          "sha256": "ae346a0702a1d84f2232adca808022f31e3f173c87315da90a0b5e33fa146e6d",
          "sha1": "d5ba4da01bf0097de246b518a2957bd8474d2e5a",
          "md5": "be411103a527e59a2668fbff611819d4"
        }
      ]
    }
  ]
}
