{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_release",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-30.0.aar",
          "url": "core_release-30.0.aar",
          "size": 36567,
          "sha512": "9dc1ac5fab66aff7760a85054b9fe35e924bc69efeab3cc4243ce4efa3be6f7d9d505287b949f3e8fb16bab07e08417f492cef19c35cb72264abf3a49512d7a0",
          "sha256": "f217f93ac87a2b774631c00b3a47f5bdc380d1a58ed670647b12caa9cc7d508b",
          "sha1": "fbbaa55e6ed8371cb401e86e046f392b325aa6aa",
          "md5": "07e246bd9a38e6cc16fa6d863996ec84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.mathrawk.libphonenumber",
          "module": "libphonenumber_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "30.0"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "30.0"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-30.0.aar",
          "url": "core_release-30.0.aar",
          "size": 36567,
          "sha512": "9dc1ac5fab66aff7760a85054b9fe35e924bc69efeab3cc4243ce4efa3be6f7d9d505287b949f3e8fb16bab07e08417f492cef19c35cb72264abf3a49512d7a0",
          "sha256": "f217f93ac87a2b774631c00b3a47f5bdc380d1a58ed670647b12caa9cc7d508b",
          "sha1": "fbbaa55e6ed8371cb401e86e046f392b325aa6aa",
          "md5": "07e246bd9a38e6cc16fa6d863996ec84"
        }
      ]
    }
  ]
}
