{
  "formatVersion": "1.1",
  "component": {
    "group": "flutter.plugins.contactsservice.contactsservice",
    "module": "contacts_service_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_profile-1.0.aar",
          "url": "contacts_service_profile-1.0.aar",
          "size": 27438,
          "sha512": "69ef7688f21d9dd814b7c3b44d1ec2ca89adf4dda473ab88d7211ea5b3375c99e167c7ab504162118e4a421afdc2bd34828e03933f321f406f70433005575166",
          "sha256": "29fcc2e7506898b24fc8f2917943d10c655d81b1e16dc457908197a78dee1e77",
          "sha1": "906ac3496e3262de2e94a3b764298418b48e7344",
          "md5": "474be9003ba6c6c3c06897ede3f8a50f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "contacts_service_profile-1.0.aar",
          "url": "contacts_service_profile-1.0.aar",
          "size": 27438,
          "sha512": "69ef7688f21d9dd814b7c3b44d1ec2ca89adf4dda473ab88d7211ea5b3375c99e167c7ab504162118e4a421afdc2bd34828e03933f321f406f70433005575166",
          "sha256": "29fcc2e7506898b24fc8f2917943d10c655d81b1e16dc457908197a78dee1e77",
          "sha1": "906ac3496e3262de2e94a3b764298418b48e7344",
          "md5": "474be9003ba6c6c3c06897ede3f8a50f"
        }
      ]
    }
  ]
}
