{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.core",
    "module": "core_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-v1.0.2.aar",
          "url": "core_release-v1.0.2.aar",
          "size": 37132,
          "sha512": "f35dd40aec35da36b1eb1c568f25ac566c2289745f147b7433137bd25e1fd1011e701f4b1a35fdc028dfc423b1c998f25baaace9a052d6729aa69f3cb1e8a6d4",
          "sha256": "e8ce8eeae3320831472deb1542a1a4a1d858419a7d33b72eff70820b5fa928d2",
          "sha1": "89ca43be249c1019fab034eeee98c76c0f6e6285",
          "md5": "6e294b4e33f7e25f5324970b1f0b83b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "com.julienvignali.phone_number",
          "module": "phone_number_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "com.xuning.native_font",
          "module": "native_font_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core_release-v1.0.2.aar",
          "url": "core_release-v1.0.2.aar",
          "size": 37132,
          "sha512": "f35dd40aec35da36b1eb1c568f25ac566c2289745f147b7433137bd25e1fd1011e701f4b1a35fdc028dfc423b1c998f25baaace9a052d6729aa69f3cb1e8a6d4",
          "sha256": "e8ce8eeae3320831472deb1542a1a4a1d858419a7d33b72eff70820b5fa928d2",
          "sha1": "89ca43be249c1019fab034eeee98c76c0f6e6285",
          "md5": "6e294b4e33f7e25f5324970b1f0b83b6"
        }
      ]
    }
  ]
}
