{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_profile-26.0.aar",
          "url": "safe_device_profile-26.0.aar",
          "size": 21451,
          "sha512": "df43a09732d9e1fea813d5c72717b65f1790fe84122bcd2d673250c0035913d300f5034b0de691d2eb51bffce266064516834904db6ce2a4d76e32eef502ff02",
          "sha256": "547a78c03992b9dd28a05ebcf062b54dac7fc824ab1ab81ce8650f780df82331",
          "sha1": "7b837bbe6f35669521db75bac5a738a743568d01",
          "md5": "51b0f86254f5b5cd069517636fec5564"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "26.0"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_profile-26.0.aar",
          "url": "safe_device_profile-26.0.aar",
          "size": 21451,
          "sha512": "df43a09732d9e1fea813d5c72717b65f1790fe84122bcd2d673250c0035913d300f5034b0de691d2eb51bffce266064516834904db6ce2a4d76e32eef502ff02",
          "sha256": "547a78c03992b9dd28a05ebcf062b54dac7fc824ab1ab81ce8650f780df82331",
          "sha1": "7b837bbe6f35669521db75bac5a738a743568d01",
          "md5": "51b0f86254f5b5cd069517636fec5564"
        }
      ]
    }
  ]
}
