{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-debug.aar",
          "url": "sqflite-1.0-debug.aar",
          "size": 44249,
          "sha512": "5781e397f82f88b2bdc403b5f689a2f35458e6bbcda3648600c7da21d7a9b41bcb816662f9a531745085eb6d71a535f725369e95ee3462281425306c9252f417",
          "sha256": "22ce713c18b52ea74166a0f0f1d0fc7b1f964f373700b1e7087e95093e0d1722",
          "sha1": "8b9918e782fddbc3c13cd0a0fc0733db5506ce8f",
          "md5": "48eadbf1beb4f628fd7f26e381c5b9fb"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-debug.aar",
          "url": "sqflite-1.0-debug.aar",
          "size": 44249,
          "sha512": "5781e397f82f88b2bdc403b5f689a2f35458e6bbcda3648600c7da21d7a9b41bcb816662f9a531745085eb6d71a535f725369e95ee3462281425306c9252f417",
          "sha256": "22ce713c18b52ea74166a0f0f1d0fc7b1f964f373700b1e7087e95093e0d1722",
          "sha1": "8b9918e782fddbc3c13cd0a0fc0733db5506ce8f",
          "md5": "48eadbf1beb4f628fd7f26e381c5b9fb"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-release.aar",
          "url": "sqflite-1.0-release.aar",
          "size": 42245,
          "sha512": "182f570801f646859f21d3cc01fe616ffcc03ff9325df04981952de38a59e577f8be2d4ac499e37e80f72d5dbcfd8d5b825fb3deb82459ec2ef59097ff307899",
          "sha256": "d88d1b80df7df14259f75ec40bfc360bacc7603a615d2360f4f538d80174c47b",
          "sha1": "b37edbf508ab388c2f1e30b7366edffd901e943b",
          "md5": "0d8f76a7fab70304f4a8beee34ac1f84"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-release.aar",
          "url": "sqflite-1.0-release.aar",
          "size": 42245,
          "sha512": "182f570801f646859f21d3cc01fe616ffcc03ff9325df04981952de38a59e577f8be2d4ac499e37e80f72d5dbcfd8d5b825fb3deb82459ec2ef59097ff307899",
          "sha256": "d88d1b80df7df14259f75ec40bfc360bacc7603a615d2360f4f538d80174c47b",
          "sha1": "b37edbf508ab388c2f1e30b7366edffd901e943b",
          "md5": "0d8f76a7fab70304f4a8beee34ac1f84"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-profile.aar",
          "url": "sqflite-1.0-profile.aar",
          "size": 42246,
          "sha512": "95b470a2967ffa74ee281b15baf3314af3dfc1e55df29c3ac9fea656ac80e5d96fa6c1c6b1447b790f2fdf23cab1ce8f949c062bce01def92c7d2a39e445c249",
          "sha256": "bbda9332e845e3d684ba3e5f266347c332bb9a985a7917b9045029f28ddac896",
          "sha1": "9a988584333c5d6b5c8efc76ca18b6f0341daf0c",
          "md5": "615bdb70ade0607c9cfea8ac411b6d97"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-1.0-profile.aar",
          "url": "sqflite-1.0-profile.aar",
          "size": 42246,
          "sha512": "95b470a2967ffa74ee281b15baf3314af3dfc1e55df29c3ac9fea656ac80e5d96fa6c1c6b1447b790f2fdf23cab1ce8f949c062bce01def92c7d2a39e445c249",
          "sha256": "bbda9332e845e3d684ba3e5f266347c332bb9a985a7917b9045029f28ddac896",
          "sha1": "9a988584333c5d6b5c8efc76ca18b6f0341daf0c",
          "md5": "615bdb70ade0607c9cfea8ac411b6d97"
        }
      ]
    }
  ]
}
