{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8957,
          "sha512": "d2417af7d9d098737f0c87c86e274776d73768e897df7541f26bc7b7659ffe134bc6bbde0efdd887be2618d5ca8c0a9b56ee8126a1614572f5d29d3ef170ebdb",
          "sha256": "0c2991efa6afe8c10aa767eba5074d710dceb576cafe1047dcbb1af12b86e9df",
          "sha1": "2a4acf04a0778ffbcdaaa61a4fad7236a85dc691",
          "md5": "9bebbe4b0bc89ce23b0486380238442d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8957,
          "sha512": "d2417af7d9d098737f0c87c86e274776d73768e897df7541f26bc7b7659ffe134bc6bbde0efdd887be2618d5ca8c0a9b56ee8126a1614572f5d29d3ef170ebdb",
          "sha256": "0c2991efa6afe8c10aa767eba5074d710dceb576cafe1047dcbb1af12b86e9df",
          "sha1": "2a4acf04a0778ffbcdaaa61a4fad7236a85dc691",
          "md5": "9bebbe4b0bc89ce23b0486380238442d"
        }
      ]
    }
  ]
}
