{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-debug.aar",
          "url": "safe_device-1.0-debug.aar",
          "size": 21735,
          "sha512": "0269130e76c79210a1cbb03a0c2a1d39f46c1f717dcc461c916a09f6a0caf2e52cfaed45df73c1da311e89d59f5ccbd0d19a14188f78219d19ab541c44eeca6d",
          "sha256": "4150ae6940df2aa6fb73955be3e6815063e49143873d4a3204fbca75db9288b7",
          "sha1": "5a3341cc69bcbd694ea1e650b2c244b8c98857cc",
          "md5": "3ce8e04f3254f3e40965c0d50d09fbb8"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-debug.aar",
          "url": "safe_device-1.0-debug.aar",
          "size": 21735,
          "sha512": "0269130e76c79210a1cbb03a0c2a1d39f46c1f717dcc461c916a09f6a0caf2e52cfaed45df73c1da311e89d59f5ccbd0d19a14188f78219d19ab541c44eeca6d",
          "sha256": "4150ae6940df2aa6fb73955be3e6815063e49143873d4a3204fbca75db9288b7",
          "sha1": "5a3341cc69bcbd694ea1e650b2c244b8c98857cc",
          "md5": "3ce8e04f3254f3e40965c0d50d09fbb8"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-release.aar",
          "url": "safe_device-1.0-release.aar",
          "size": 21448,
          "sha512": "f8a82a3ece1b78a5e9221b6c5af363cf9a82de78f6f94fcbdb54291ab2606baada1e034302543a2144b2be4b76341f99c31027ed8fb1de2c60f2eef6d17c78c5",
          "sha256": "f43c61b829385e76e54f4b6575f7c1c6068db9aa4c2920f2b0629a9d2542650a",
          "sha1": "740303d174780aa71c37ed2556a2c4724ae2c361",
          "md5": "79ac3cb3cf2cf244fe7eaf20953e637a"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-release.aar",
          "url": "safe_device-1.0-release.aar",
          "size": 21448,
          "sha512": "f8a82a3ece1b78a5e9221b6c5af363cf9a82de78f6f94fcbdb54291ab2606baada1e034302543a2144b2be4b76341f99c31027ed8fb1de2c60f2eef6d17c78c5",
          "sha256": "f43c61b829385e76e54f4b6575f7c1c6068db9aa4c2920f2b0629a9d2542650a",
          "sha1": "740303d174780aa71c37ed2556a2c4724ae2c361",
          "md5": "79ac3cb3cf2cf244fe7eaf20953e637a"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-profile.aar",
          "url": "safe_device-1.0-profile.aar",
          "size": 21451,
          "sha512": "df43a09732d9e1fea813d5c72717b65f1790fe84122bcd2d673250c0035913d300f5034b0de691d2eb51bffce266064516834904db6ce2a4d76e32eef502ff02",
          "sha256": "547a78c03992b9dd28a05ebcf062b54dac7fc824ab1ab81ce8650f780df82331",
          "sha1": "7b837bbe6f35669521db75bac5a738a743568d01",
          "md5": "51b0f86254f5b5cd069517636fec5564"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device-1.0-profile.aar",
          "url": "safe_device-1.0-profile.aar",
          "size": 21451,
          "sha512": "df43a09732d9e1fea813d5c72717b65f1790fe84122bcd2d673250c0035913d300f5034b0de691d2eb51bffce266064516834904db6ce2a4d76e32eef502ff02",
          "sha256": "547a78c03992b9dd28a05ebcf062b54dac7fc824ab1ab81ce8650f780df82331",
          "sha1": "7b837bbe6f35669521db75bac5a738a743568d01",
          "md5": "51b0f86254f5b5cd069517636fec5564"
        }
      ]
    }
  ]
}
