{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25028,
          "sha512": "3a94b64e3a55a6cbba2cb0395393308f307cd657c69f8fd15aab4938fc1d9bba03a6daf9973d31a7c11f836464433908f99c1685ebc66eb472c9b4b80fbdaab8",
          "sha256": "de5d4aa41e1f45b6f348c6fe5c33a98a5fce9e12a2a9b1a7ec98de150ec950df",
          "sha1": "1ba6df7077342965d0dd8f805b3048bc1e993c3a",
          "md5": "38db04be27b150021b44ec3762f77403"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25028,
          "sha512": "3a94b64e3a55a6cbba2cb0395393308f307cd657c69f8fd15aab4938fc1d9bba03a6daf9973d31a7c11f836464433908f99c1685ebc66eb472c9b4b80fbdaab8",
          "sha256": "de5d4aa41e1f45b6f348c6fe5c33a98a5fce9e12a2a9b1a7ec98de150ec950df",
          "sha1": "1ba6df7077342965d0dd8f805b3048bc1e993c3a",
          "md5": "38db04be27b150021b44ec3762f77403"
        }
      ]
    }
  ]
}
