{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.wallet_suppression",
    "module": "wallet_suppression_profile",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_profile-26.0.aar",
          "url": "wallet_suppression_profile-26.0.aar",
          "size": 6930,
          "sha512": "33e7926ea2dbb2e57dd03b50092aeebc621aff3f0c5b61105a65286cdf119bf922318fde9e594a3f1028e72a78fafccd5e12f67eb9129e165d1f3a44d21c555f",
          "sha256": "97989cae8c1dd314b1e74d93f55dfd26ef16bbd82106454fdf6701ebe10409bd",
          "sha1": "e340a964e021cdaf279e1b127fd375beabc6fb49",
          "md5": "c0c8f635f478bbbbe3332e2857fee546"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "wallet_suppression_profile-26.0.aar",
          "url": "wallet_suppression_profile-26.0.aar",
          "size": 6930,
          "sha512": "33e7926ea2dbb2e57dd03b50092aeebc621aff3f0c5b61105a65286cdf119bf922318fde9e594a3f1028e72a78fafccd5e12f67eb9129e165d1f3a44d21c555f",
          "sha256": "97989cae8c1dd314b1e74d93f55dfd26ef16bbd82106454fdf6701ebe10409bd",
          "sha1": "e340a964e021cdaf279e1b127fd375beabc6fb49",
          "md5": "c0c8f635f478bbbbe3332e2857fee546"
        }
      ]
    }
  ]
}
