{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mathrawk.libphonenumber",
    "module": "libphonenumber",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-debug.aar",
          "url": "libphonenumber-26.0-debug.aar",
          "size": 7518,
          "sha512": "5fa2741bffe855719a26a53b920d7b9ff6d4d077eedb6531d3ee1f98d556a1e008f38b87d95896a5b117d058c98f129eba55faf151b3c0c34f58fed9cb1f5bcb",
          "sha256": "555c8894b7943aaba2b7b5395c91909020e94f3bf6e84191d7fe2ec91c99a216",
          "sha1": "3f20cad716eac856ce291462d9a442cf084457a6",
          "md5": "2988b5b0083c9fb8728ed753292f5f2a"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-debug.aar",
          "url": "libphonenumber-26.0-debug.aar",
          "size": 7518,
          "sha512": "5fa2741bffe855719a26a53b920d7b9ff6d4d077eedb6531d3ee1f98d556a1e008f38b87d95896a5b117d058c98f129eba55faf151b3c0c34f58fed9cb1f5bcb",
          "sha256": "555c8894b7943aaba2b7b5395c91909020e94f3bf6e84191d7fe2ec91c99a216",
          "sha1": "3f20cad716eac856ce291462d9a442cf084457a6",
          "md5": "2988b5b0083c9fb8728ed753292f5f2a"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-release.aar",
          "url": "libphonenumber-26.0-release.aar",
          "size": 7198,
          "sha512": "7ba08da908dec023ffea36ecdc646918cd332b31f1c9670f0091f82916091a8e57d481a1d2c61b66e690aa73c90eaf063648c07d9c903a38250c6f142eeda26d",
          "sha256": "4c8a53e3f52cc9cd43398ccafd022c0e3d467aae356d1ca0eaa67251c87c87b7",
          "sha1": "4b8ed0c410eeac4acc7917a2f571d82e8919729e",
          "md5": "e7ed3ce879179b766f241ad11f38d920"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-release.aar",
          "url": "libphonenumber-26.0-release.aar",
          "size": 7198,
          "sha512": "7ba08da908dec023ffea36ecdc646918cd332b31f1c9670f0091f82916091a8e57d481a1d2c61b66e690aa73c90eaf063648c07d9c903a38250c6f142eeda26d",
          "sha256": "4c8a53e3f52cc9cd43398ccafd022c0e3d467aae356d1ca0eaa67251c87c87b7",
          "sha1": "4b8ed0c410eeac4acc7917a2f571d82e8919729e",
          "md5": "e7ed3ce879179b766f241ad11f38d920"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-profile.aar",
          "url": "libphonenumber-26.0-profile.aar",
          "size": 7199,
          "sha512": "a9c0bed40d1d79cba7f40376027826192c4f59d97407387b0d48c1793724a13a071ce045b098371df7b6f2892e4474c4f43577e4397df5d34f98ea991cc2900f",
          "sha256": "ef3ea6af76285f94e08db9b49c61b2e0d04c109d6df07201d6dcc496c5119999",
          "sha1": "388dbc6a544f9dac2415ef67978f32fa04b93c0c",
          "md5": "6aa1c2197a9699fc159bfa54da942f08"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.32"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "carrier",
          "version": {
            "requires": "1.158"
          }
        }
      ],
      "files": [
        {
          "name": "libphonenumber-26.0-profile.aar",
          "url": "libphonenumber-26.0-profile.aar",
          "size": 7199,
          "sha512": "a9c0bed40d1d79cba7f40376027826192c4f59d97407387b0d48c1793724a13a071ce045b098371df7b6f2892e4474c4f43577e4397df5d34f98ea991cc2900f",
          "sha256": "ef3ea6af76285f94e08db9b49c61b2e0d04c109d6df07201d6dcc496c5119999",
          "sha1": "388dbc6a544f9dac2415ef67978f32fa04b93c0c",
          "md5": "6aa1c2197a9699fc159bfa54da942f08"
        }
      ]
    }
  ]
}
