{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.appsettings",
    "module": "app_settings_debug",
    "version": "30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_debug-30.0.aar",
          "url": "app_settings_debug-30.0.aar",
          "size": 8504,
          "sha512": "a455a762abf81d76b53fb68682d393b3cc8f73e16a4ce449aa5161ef5eb249f0fdba9f13e5e8d5f139020a26badc622a5ad63368832bf4fbc65c594db9e2c3d2",
          "sha256": "69c8ea5fdfc75da647ff932ea3ff779fe5b99ef6df6fa64386db53504290315c",
          "sha1": "c14985bdadceaa34e145cb3efe10ad12bf9392e7",
          "md5": "207d98f81cf0f2dd6a62a0881d531c93"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-800594f1f4a6674010a6f1603c07a919b4d7ebd7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app_settings_debug-30.0.aar",
          "url": "app_settings_debug-30.0.aar",
          "size": 8504,
          "sha512": "a455a762abf81d76b53fb68682d393b3cc8f73e16a4ce449aa5161ef5eb249f0fdba9f13e5e8d5f139020a26badc622a5ad63368832bf4fbc65c594db9e2c3d2",
          "sha256": "69c8ea5fdfc75da647ff932ea3ff779fe5b99ef6df6fa64386db53504290315c",
          "sha1": "c14985bdadceaa34e145cb3efe10ad12bf9392e7",
          "md5": "207d98f81cf0f2dd6a62a0881d531c93"
        }
      ]
    }
  ]
}
