{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_plus_release",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-26.0.aar",
          "url": "connectivity_plus_release-26.0.aar",
          "size": 8956,
          "sha512": "3b1426a8079ec816ef7826efdcaccda5a82a1e8a32b25fa0ffcef514db212768fa449e5d8c6befa314bd3a28dad5e1331438739463be8f9a3606a5bcc6cc8380",
          "sha256": "ca7caea945d3ec1ed5d5df3c7b166f40b29314dca14e980800910ad1b6ebcb2f",
          "sha1": "48b3b0dc224750715fda3c55d68b5d0ad6645773",
          "md5": "16214470e8ac08e2497ed8e74b58f17f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-26.0.aar",
          "url": "connectivity_plus_release-26.0.aar",
          "size": 8956,
          "sha512": "3b1426a8079ec816ef7826efdcaccda5a82a1e8a32b25fa0ffcef514db212768fa449e5d8c6befa314bd3a28dad5e1331438739463be8f9a3606a5bcc6cc8380",
          "sha256": "ca7caea945d3ec1ed5d5df3c7b166f40b29314dca14e980800910ad1b6ebcb2f",
          "sha1": "48b3b0dc224750715fda3c55d68b5d0ad6645773",
          "md5": "16214470e8ac08e2497ed8e74b58f17f"
        }
      ]
    }
  ]
}
