{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device_release",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-v1.0.2.aar",
          "url": "safe_device_release-v1.0.2.aar",
          "size": 21584,
          "sha512": "084266077dfc2b4989e0a56fe38d465229ab26ff8822f454d656664757b876720bebb143e7d51d59338970de41690bd9d68b709583d4c3d1194005bb18790572",
          "sha256": "87ced41fe7dd3cd38d708579166f718aaa2ceb973d9eed80be612b10f8c42403",
          "sha1": "6322eb85cd1752cd76a4d21a5ed5273282eec236",
          "md5": "83e7829b9e19706c6aec08146cc13b0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.wongpiwat.trust_location",
          "module": "trust_location_release",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_release-v1.0.2.aar",
          "url": "safe_device_release-v1.0.2.aar",
          "size": 21584,
          "sha512": "084266077dfc2b4989e0a56fe38d465229ab26ff8822f454d656664757b876720bebb143e7d51d59338970de41690bd9d68b709583d4c3d1194005bb18790572",
          "sha256": "87ced41fe7dd3cd38d708579166f718aaa2ceb973d9eed80be612b10f8c42403",
          "sha1": "6322eb85cd1752cd76a4d21a5ed5273282eec236",
          "md5": "83e7829b9e19706c6aec08146cc13b0a"
        }
      ]
    }
  ]
}
