{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_debug",
    "version": "v1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.2.aar",
          "url": "screenshot_prevention_debug-v1.0.2.aar",
          "size": 32379,
          "sha512": "4fcaeeab8d998b77279c36bbe26724f48af47e198b5f9bbad3b8ce0fd9efd22d717aed772a5ca10a8f26c094bd54603eb62c888f2bf2cda29b6384d6d6fe365e",
          "sha256": "e5654bc251bde8fe068ee68c714eb1ffef7f39d1bc50cc145c4fe8fe45bb9cda",
          "sha1": "4e599e42d1ba7e5c34ea73af908b0a622cf21368",
          "md5": "1e1240acf6a184621bdcfc17adf4b46a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.2.aar",
          "url": "screenshot_prevention_debug-v1.0.2.aar",
          "size": 32379,
          "sha512": "4fcaeeab8d998b77279c36bbe26724f48af47e198b5f9bbad3b8ce0fd9efd22d717aed772a5ca10a8f26c094bd54603eb62c888f2bf2cda29b6384d6d6fe365e",
          "sha256": "e5654bc251bde8fe068ee68c714eb1ffef7f39d1bc50cc145c4fe8fe45bb9cda",
          "sha1": "4e599e42d1ba7e5c34ea73af908b0a622cf21368",
          "md5": "1e1240acf6a184621bdcfc17adf4b46a"
        }
      ]
    }
  ]
}
