{
  "formatVersion": "1.1",
  "component": {
    "group": "io.tixngo.screenshot_prevention",
    "module": "screenshot_prevention_debug",
    "version": "v1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.4.aar",
          "url": "screenshot_prevention_debug-v1.0.4.aar",
          "size": 59014,
          "sha512": "fc2df2d57c18672d04b6acdf4c9c0f09f969a43df65196aa349bee54e37c8ada1b2ca9f6906ae176d5cacc223ceb05c21c8ce160b3cda0d5838afaae5b24d0ad",
          "sha256": "4cc93e42cc9bc97f7e393c90463c9e4587d8993939d7291cea59122cc4d937a8",
          "sha1": "dd96f7ff6cc3d264d3ed886317e704d3abf519be",
          "md5": "8589d3696cec607f46e16ffe994040fd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "io.tixngo.core",
          "module": "core_debug",
          "version": {
            "requires": "v1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "screenshot_prevention_debug-v1.0.4.aar",
          "url": "screenshot_prevention_debug-v1.0.4.aar",
          "size": 59014,
          "sha512": "fc2df2d57c18672d04b6acdf4c9c0f09f969a43df65196aa349bee54e37c8ada1b2ca9f6906ae176d5cacc223ceb05c21c8ce160b3cda0d5838afaae5b24d0ad",
          "sha256": "4cc93e42cc9bc97f7e393c90463c9e4587d8993939d7291cea59122cc4d937a8",
          "sha1": "dd96f7ff6cc3d264d3ed886317e704d3abf519be",
          "md5": "8589d3696cec607f46e16ffe994040fd"
        }
      ]
    }
  ]
}
